'use strict';

// Progressive disclosure and explicit review at consequential changes.
function operationsNavigation(section){
  const links=ids=>OPS_NAV.filter(([id])=>ids.includes(id)).map(([id,ic,t])=>`<a href="#admin/${id}" class="${section===id?'active':''}" ${section===id?'aria-current="page"':''}>${icon(ic)}${t}</a>`).join('');
  return `${links(['roadmap'])}<div class="nav-group-label">Daily operations</div>${links(['overview','orders','fulfillment','support'])}<details class="nav-group" ${['stores','compare','insights'].includes(section)?'open':''}><summary>Network insights</summary>${links(['stores','compare','insights'])}</details><details class="nav-group" ${['loyalty','campaigns','customers','coupons','campaign-results'].includes(section)?'open':''}><summary>Loyalty & growth</summary>${links(['loyalty','campaigns','coupons','campaign-results','customers'])}</details><details class="nav-group" ${['menu','customers','offers','campaigns','settings'].includes(section)?'open':''}><summary>Manage & configure</summary>${links(['menu','offers','settings'])}</details>`;
}
function pricingFingerprint(){return JSON.stringify({program:state.loyalty,reward:state.rewardCatalog.find(r=>r.id===state.reward),member:state.memberMeta.alex,points:state.points,store:state.customerStoreId,mode:state.mode,items:state.cart.map(x=>[x.id,x.qty,unit(x),product(x.id)?.available]),delivery:customerStore().deliveryFee,promo:state.promo,paused:state.paused,fulfillment:customerStore()[state.mode.toLowerCase()],ingredients:customerStore().ingredients,group:state.groupCheckoutId,coupon:state.coupons.find(c=>c.code===checkout.promo),campaign:state.campaigns.find(c=>c.code===checkout.promo||c.id===state.coupons.find(x=>x.code===checkout.promo)?.campaignId)});}
function checkoutReviewNotice(){const next=pricingFingerprint();if(checkout.quote&&checkout.quote!==next)checkout.priceReview=true;checkout.quote=next;return checkout.priceReview?`<div class="notice price-review" role="alert"><strong>Your order details have changed.</strong><p>Review the current items, store availability, fees and total before placing this order. Your bag and payment selection are preserved.</p><button type="button" class="btn secondary" data-action="accept-price-review">I’ve reviewed the updated order</button></div>`:'';}
function targetUnit(item,store){const p=store.menu.find(p=>p.id===item.id);return p?p.price+(item.options?.size==='Small'?-200:item.options?.size==='Mega'?300:0)+(item.options?.crust==='Cauliflower'?200:0):0;}
function chooseCustomerStore(id){const s=storeById(id);if(!s||id===state.customerStoreId)return;if(!count())return commitCustomerStore(id);const current=customerStore(),nextMode=!s[state.mode.toLowerCase()]?(s.delivery?'Delivery':'Pickup'):state.mode;
  closeModal();openModal('Review your store change',`<div class="modal-body"><p><strong>${esc(current.name)}</strong> → <strong>${esc(s.name)}</strong></p><p class="small muted">Your pizza choices stay in your bag. Review what changes before continuing.</p><div class="admin-table-wrap"><table class="history-table"><thead><tr><th>Bag item</th><th>Now</th><th>New store</th></tr></thead><tbody>${state.cart.map(x=>{const p=s.menu.find(p=>p.id===x.id);return `<tr><td>${x.qty} × ${esc(product(x.id).name)}</td><td>${money(unit(x)*x.qty)}</td><td>${p?.available?money(targetUnit(x,s)*x.qty):'<strong class="red">Unavailable</strong>'}</td></tr>`;}).join('')}</tbody></table></div><div class="summary-row"><span>Food subtotal</span><strong>${money(state.cart.reduce((n,x)=>n+targetUnit(x,s)*x.qty,0))}</strong></div><div class="summary-row"><span>Fulfillment</span><strong>${nextMode}${nextMode!==state.mode?' (changed)':''}</strong></div><div class="summary-row"><span>Delivery fee</span><strong>${nextMode==='Delivery'?money(s.deliveryFee):'Free pickup'}</strong></div><div class="summary-row"><span>Preparation estimate</span><strong>${s.prep}–${s.prep+5} min</strong></div><p class="notice">${s.paused?'This store has paused ordering. ':''}${s.promo?'MOD10 is available.':'MOD10 is unavailable here.'} Rewards and the complete tax-inclusive total will be rechecked at checkout. Unavailable items must be removed; nothing is substituted.</p></div><div class="modal-foot row wrap"><button class="btn secondary" data-action="close">Keep current store</button><button class="btn" data-action="confirm-store-change" data-id="${id}">Use this store</button></div>`);
}
function requestCancelOrder(o){if(!o||o.canceled)return;if(modal.open)closeModal();openModal('Review cancellation & refund',`<div class="modal-body"><p><strong>${esc(o.id)}</strong> · ${esc(o.store)}</p><p class="small muted">Current status: ${orderStatus(o)}. Review the full refund below before canceling this demo order.</p><div class="summary-row"><span>Order total</span><strong>${money(o.totals.total)}</strong></div><div class="summary-row"><span>Gift funds restored</span><strong>${money(o.totals.gift)}</strong></div><div class="summary-row"><span>Service credit restored</span><strong>${money(o.totals.credit)}</strong></div><div class="summary-row"><span>Demo payment refunded</span><strong>${money(o.totals.due)}</strong></div><div class="summary-row"><span>Redeemed points restored</span><strong>${o.totals.pointsSpent}</strong></div><div class="summary-row"><span>Earned points reversed</span><strong>${o.pointsEarned||0}</strong></div><p class="notice">${o.seed?'This is a seeded sample order; no real or seeded customer funds were charged.':'This will update the local customer wallet and order history.'} The order will be marked canceled.</p></div><div class="modal-foot row wrap"><button class="btn secondary" data-action="close">Keep order</button><button class="btn" data-action="confirm-cancel-order" data-id="${o.id}">Confirm demo refund</button></div>`);}
document.addEventListener('click',e=>{const el=e.target.closest('[data-action]');if(!el||el.disabled)return;
  if(el.dataset.action==='confirm-store-change'){checkout.quote=null;checkout.priceReview=false;commitCustomerStore(el.dataset.id);}
  if(el.dataset.action==='accept-price-review'){checkout.quote=pricingFingerprint();checkout.priceReview=false;render();toast('Updated order reviewed. You can now place it.');}
  if(el.dataset.action==='confirm-cancel-order')cancelOrder(orderById(el.dataset.id));
});
