'use strict';
// Shared loyalty rules: HQ configuration feeds customer checkout and store recovery.
function initializeLoyalty(){
 state.loyalty ||= {rate:1,dailyCap:500,tiers:false,silver:20000,gold:50000,silverMultiplier:1.25,goldMultiplier:1.5};
 state.rewardCatalog ||= REWARD_CATALOG.map(r=>({...r,enabled:true,kind:r.id==='delivery'?'delivery':r.id==='pizza'||r.id==='cake'?'item':'fixed',value:r.id==='pizza'?1249:r.id==='cake'?399:r.id==='five'?500:299,item:r.id==='cake'?'cake':'',category:r.id==='pizza'?'Pizzas':'',min:0,tier:'Member',stores:state.stores.map(s=>s.id),start:'',end:'',limit:0}));
 state.memberMeta ||= {};state.recovery ||= [{id:'recovery-sample-sea',customer:'guest-1',storeId:'sea',order:'',kind:'points',amount:35,reason:'Sample case: missing topping on a recent visit.',status:'Pending',date:Date.now()},{id:'recovery-sample-bel',customer:'guest-2',storeId:'bel',order:'',kind:'credit',amount:500,reason:'Sample case: pickup handoff took longer than promised.',status:'Pending',date:Date.now()}];state.loyaltyLedger ||= [];
 for(const c of loyaltyMembers()){state.memberMeta[c.id] ||= {active:true,consent:c.id==='alex'?state.profile.marketing:false};if(!state.loyaltyLedger.some(l=>l.customer===c.id&&l.type==='opening'))state.loyaltyLedger.push({id:uid(),customer:c.id,delta:c.points,balance:c.points,type:'opening',reason:'Opening balance at loyalty upgrade',date:Date.now(),storeId:null});}
}
function loyaltyMembers(){return [{id:'alex',...state.profile,points:state.points,credit:state.credit},...state.customers];}
function memberBalance(id){return id==='alex'?state:state.customers.find(c=>c.id===id);}
function memberStats(id){const orders=state.orders.filter(o=>o.customerId===id&&!o.canceled&&stage(o)===4);return {visits:orders.length,spend:orders.reduce((n,o)=>n+orderSales(o),0),last:Math.max(0,...orders.map(o=>o.created))};}
function memberTier(id='alex'){const spend=memberStats(id).spend,p=state.loyalty;return !p.tiers?'Member':spend>=p.gold?'Gold':spend>=p.silver?'Silver':'Member';}
function earningRate(id='alex'){const tier=memberTier(id),p=state.loyalty;return p.rate*(tier==='Gold'?p.goldMultiplier:tier==='Silver'?p.silverMultiplier:1);}
function pointEntry(id,delta,type,reason,storeId=null){const c=memberBalance(id);if(!c||!Number.isInteger(delta)||c.points+delta<0)throw Error('Not enough points for this change.');c.points+=delta;state.loyaltyLedger.unshift({id:uid(),customer:id,delta,balance:c.points,type,reason,date:Date.now(),storeId});if(id==='alex')state.ledger.unshift({id:uid(),title:reason,detail:`${delta>=0?'+':''}${delta} points`,date:Date.now()});}
function rewardAvailable(r,id='alex',storeId=state.customerStoreId){if(!r?.enabled)return 'Reward paused';if(!state.memberMeta[id]?.active)return 'Membership paused';if(!r.stores.includes(storeId))return 'Not at this store';const day=new Date().toLocaleDateString('en-CA');if(r.start&&day<r.start)return 'Not started';if(r.end&&day>r.end)return 'Reward expired';if(['Member','Silver','Gold'].indexOf(memberTier(id))<['Member','Silver','Gold'].indexOf(r.tier))return `${r.tier} members only`;const uses=state.orders.filter(o=>o.customerId===id&&!o.canceled&&o.rewardId===r.id).length;if(r.limit&&uses>=r.limit)return 'Member limit reached';return '';}
function rewardQuote(id=state.reward){const r=state.rewardCatalog.find(r=>r.id===id),bad=rewardAvailable(r);const fail=reason=>({valid:false,reason,discount:0,points:0,delivery:false});if(!r||bad)return fail(bad||'Choose a reward');if(state.points<r.points)return fail(`${r.points-state.points} more points needed`);const subtotal=state.cart.reduce((n,x)=>n+unit(x)*x.qty,0);if(subtotal<r.min)return fail(`Spend at least ${money(r.min)}`);let discount=0;
 if(r.kind==='delivery'){if(state.mode!=='Delivery')return fail('Delivery orders only');discount=subtotal?customerStore().deliveryFee:0;}
 if(r.kind==='fixed')discount=Math.min(subtotal,r.value);
 if(r.kind==='percent')discount=Math.round(subtotal*r.value/100);
 if(r.kind==='item'){const prices=state.cart.filter(x=>(!r.item||x.id===r.item)&&(!r.category||product(x.id)?.category===r.category)).map(unit);if(!prices.length)return fail(`Add ${r.item?product(r.item)?.name:r.category||'a qualifying item'}`);discount=Math.min(r.value,Math.min(...prices));}
 return discount>0?{valid:true,reason:'',discount,points:r.points,delivery:r.kind==='delivery'}:fail('Add qualifying items');
}
function earnEstimate(o,id=o.customerId||'alex'){if(!state.memberMeta[id]?.active)return 0;return Math.floor(Math.max(0,o.totals.subtotal-(o.totals.merchandiseDiscount??o.totals.discount))/100*(o.earnRate??earningRate(id)));}
function awardOrderPoints(o){const id=o.customerId||'alex',today=new Date().toDateString(),used=state.loyaltyLedger.filter(l=>l.customer===id&&l.type==='earn'&&new Date(l.date).toDateString()===today).reduce((n,l)=>n+l.delta,0);o.pointsEarned=Math.min(earnEstimate(o),Math.max(0,(o.earnCap??state.loyalty.dailyCap)-used));o.earned=true;o.completedAt=Date.now();pointEntry(id,o.pointsEarned,'earn',`Order ${o.id} completed`,o.storeId);}
function customerRewardCards(){const rewards=state.rewardCatalog.filter(r=>r.enabled);return `<div class="section-head"><h2>Pick your next happy.</h2><span class="pill">${memberTier()} member</span></div><div class="reward-shop">${rewards.map(r=>{const reason=rewardAvailable(r),need=Math.max(0,r.points-state.points);return `<article class="reward-product"><img src="${menuImage(r.image||'custom')}" alt=""><div><span class="pill">${r.points} points</span><h3>${esc(r.name)}</h3><p>${esc(r.desc)}</p><p class="small muted">${r.min?`Minimum ${money(r.min)} · `:''}${r.end?`Until ${r.end} · `:''}${r.kind==='item'?`Up to ${money(r.value)} off one item`:r.kind==='percent'?`${r.value}% off`:r.kind==='delivery'?'Delivery fee waived':money(r.value)+' off'} · One reward per order</p><button class="btn secondary" data-action="reward" data-id="${r.id}" ${(reason||need)&&state.reward!==r.id?'disabled':''}>${state.reward===r.id?'Selected · Remove':reason|| (need?need+' points to go':'Use reward')}</button></div></article>`}).join('')}</div>`;}
const LOYALTY_TABS=[['program','Program rules'],['catalog','Reward catalog'],['members','Members & audiences'],['recovery','Recovery approvals'],['report','Activity & results']];
let loyaltyTab='program',memberSearch='',memberSegment='all';
function loyaltyAdmin(){return `<div class="section-head"><div><span class="eyebrow red">LOYALTY & GUEST GROWTH</span><h2>One program. Every MOD moment.</h2><p class="muted">Shared rules, local participation and a clear record of every points change.</p></div><a class="btn secondary" href="#rewards">Customer preview →</a></div><div class="segmented loyalty-tabs">${LOYALTY_TABS.map(([id,n])=>`<button data-loyalty-tab="${id}" class="${id===loyaltyTab?'selected':''}">${n}</button>`).join('')}</div>${loyaltyTab==='program'?loyaltyProgram():loyaltyTab==='catalog'?loyaltyCatalog():loyaltyTab==='members'?loyaltyMemberPage():loyaltyTab==='recovery'?recoveryPage():loyaltyReport()}`;}
function lf(name,label,value,min=0,max=10000,step=1){return `<div class="field"><label for="loyalty-${name}">${label}</label><input id="loyalty-${name}" name="${name}" type="number" value="${value}" min="${min}" max="${max}" step="${step}" required></div>`;}
function loyaltyProgram(){const p=state.loyalty;return `<div class="ops-two"><form class="card" data-loyalty-form="program"><h2>Earn, then enjoy.</h2><p class="muted small">Network-wide rules. Updates apply to new orders; placed orders retain their earning rate and cap.</p><div class="fields-two">${lf('rate','Points per $1 after discounts',p.rate,0,20,.25)}${lf('dailyCap','Daily purchase-points cap per member',p.dailyCap,1,10000)}</div><label class="check-line"><input name="tiers" type="checkbox" ${p.tiers?'checked':''}>Enable spend-based tiers</label><details ${p.tiers?'open':''}><summary>Tier thresholds & multipliers</summary><p class="small muted">Based on completed, non-refunded merchandise spend in this prototype.</p><div class="fields-two">${lf('silver','Silver lifetime spend ($)',p.silver/100,1,100000,.01)}${lf('gold','Gold lifetime spend ($)',p.gold/100,1,100000,.01)}${lf('silverMultiplier','Silver earning multiplier',p.silverMultiplier,1,5,.25)}${lf('goldMultiplier','Gold earning multiplier',p.goldMultiplier,1,5,.25)}</div></details><button class="btn">Save program rules</button><p class="error" data-loyalty-error></p></form><section class="card"><h2>Clear customer promises.</h2><div class="audit-item">Points arrive when the order is completed, once per order.</div><div class="audit-item">Tax, tips and delivery fees do not earn points. Gift funds and service credits are payment tenders, not discounts.</div><div class="audit-item">One points reward or one deal per order. No silent stacking.</div><div class="audit-item">Refunds restore redeemed points and reverse earned points. Bonuses and receipt claims are separate from the purchase cap.</div><div class="audit-item">Points do not expire in this version. Reward validity dates are configurable.</div></section></div>`;}
function loyaltyCatalog(){return `<div class="section-head"><p class="muted">${ops.store==='all'?'All locations':esc(storeById(ops.store).name)} · Rules are rechecked at checkout.</p><button class="btn" data-loyalty-action="edit-reward">Create reward</button></div><div class="campaign-grid">${state.rewardCatalog.filter(r=>ops.store==='all'||r.stores.includes(ops.store)).map(r=>`<section class="card"><div class="row between"><span class="pill ${r.enabled?'green':''}">${r.enabled?'Active':'Paused'}</span><strong>${r.points} points</strong></div><h2>${esc(r.name)}</h2><p>${esc(r.desc)}</p><div class="store-facts"><span>Type<strong>${r.kind}</strong></span><span>Store participation<strong>${r.stores.length} / ${state.stores.length}</strong></span><span>Minimum spend<strong>${money(r.min)}</strong></span><span>Member limit<strong>${r.limit||'No limit'}</strong></span></div><button class="btn secondary" data-loyalty-action="edit-reward" data-id="${r.id}">Edit rules</button> <button class="text-btn" data-loyalty-action="toggle-reward" data-id="${r.id}">${r.enabled?'Pause':'Activate'}</button></section>`).join('')}</div>`;}
function rewardEditor(id){const r=state.rewardCatalog.find(r=>r.id===id)||{name:'',desc:'',points:100,kind:'fixed',value:500,min:0,item:'',category:'',tier:'Member',stores:state.stores.map(s=>s.id),start:'',end:'',limit:0,enabled:true};const select=(name,label,values,value)=>`<div class="field"><label for="reward-${name}">${label}</label><select id="reward-${name}" name="${name}">${values.map(([v,n])=>`<option value="${esc(v)}" ${v===value?'selected':''}>${esc(n)}</option>`).join('')}</select></div>`;openModal(id?'Edit reward rules':'Create a reward',`<form data-loyalty-form="reward" data-id="${id||''}"><div class="modal-body"><div class="field"><label for="reward-name">Reward name</label><input id="reward-name" name="name" value="${esc(r.name)}" maxlength="65" required></div><div class="field"><label for="reward-desc">Description</label><input id="reward-desc" name="desc" value="${esc(r.desc)}" maxlength="160" required></div><div class="fields-two">${lf('points','Points required',r.points,1,10000)}${select('kind','Reward type',[['fixed','Dollar discount'],['percent','Percentage discount'],['item','One qualifying item'],['delivery','Free delivery']],r.kind)}${lf('value','Value ($), item cap ($), or percentage',r.kind==='percent'?r.value:r.value/100,0,1000,.01)}${lf('min','Minimum merchandise spend ($)',r.min/100,0,1000,.01)}${select('item','Qualifying item (item rewards)',[['','Any item'],...state.menu.map(p=>[p.id,p.name])],r.item)}${select('category','Qualifying category (item rewards)',[['','Any category'],...MENU_CATEGORIES.map(c=>[c,c])],r.category)}${select('tier','Minimum tier',['Member','Silver','Gold'].map(t=>[t,t]),r.tier)}${lf('limit','Uses per member (0 = unlimited)',r.limit,0,100)}<div class="field"><label for="reward-start">Start date</label><input id="reward-start" name="start" type="date" value="${r.start}"></div><div class="field"><label for="reward-end">Last valid date</label><input id="reward-end" name="end" type="date" value="${r.end}"></div></div><h3>Participating stores</h3><div class="compare-picks">${state.stores.map(s=>`<label><input type="checkbox" name="stores" value="${s.id}" ${r.stores.includes(s.id)?'checked':''}>${esc(s.name)}</label>`).join('')}</div><label class="check-line"><input name="enabled" type="checkbox" ${r.enabled?'checked':''}>Active in the customer app</label><p class="small muted">Item rewards cover one cheapest qualifying unit, up to the cap. Delivery rewards waive the actual delivery fee.</p><p class="error" data-loyalty-error></p></div><div class="modal-foot"><button class="btn full">Save reward</button></div></form>`);}
function scopedMembers(){const sid=managerContext()?.store.id||ops.store;return loyaltyMembers().filter(c=>sid==='all'||state.orders.some(o=>o.customerId===c.id&&o.storeId===sid));}
function segmentMatch(c){const m=memberStats(c.id);return memberSegment==='all'||memberSegment==='lapsed'&&m.last&&Date.now()-m.last>14*DAY||memberSegment==='regular'&&m.visits>=5||memberSegment==='ready'&&state.rewardCatalog.some(r=>!rewardAvailable(r,c.id,ops.store==='all'?state.customerStoreId:ops.store)&&c.points>=r.points)||memberSegment==='consented'&&(c.id==='alex'?state.profile.marketing:state.memberMeta[c.id].consent);}
function loyaltyMemberPage(){const members=scopedMembers().filter(segmentMatch).filter(c=>(c.name+' '+c.email).toLowerCase().includes(memberSearch.toLowerCase()));return `<section class="card"><div class="row between wrap"><h2>Know the person, not just the points.</h2><span class="pill">${members.length} members</span></div><div class="fields-two"><div class="field"><label for="loyalty-search">Find a member</label><input id="loyalty-search" value="${esc(memberSearch)}" placeholder="Name or email"></div><div class="field"><label for="loyalty-segment">Audience</label><select id="loyalty-segment">${[['all','All members'],['regular','Regulars · 5+ completed visits'],['lapsed','Lapsed · no visit in 14 days'],['ready','Can afford an eligible reward'],['consented','Marketing consent given']].map(([v,n])=>`<option value="${v}" ${v===memberSegment?'selected':''}>${n}</option>`).join('')}</select></div></div><p class="small muted">History and balances are member-wide. Store selection limits membership to guests with orders at that store. Audience counts do not imply consent to contact.</p><div class="admin-table-wrap"><table class="admin-table"><thead><tr><th>Member</th><th>Tier</th><th>Points</th><th>Visits / spend</th><th>Marketing</th><th></th></tr></thead><tbody>${members.map(c=>{const m=memberStats(c.id);return `<tr><td>${esc(c.name)}<small>${esc(c.email)}</small></td><td>${memberTier(c.id)}</td><td>${c.points}</td><td>${m.visits} / ${money(m.spend)}</td><td>${(c.id==='alex'?state.profile.marketing:state.memberMeta[c.id].consent)?'Opted in':'Not opted in'}</td><td><button class="text-btn" data-loyalty-action="member" data-id="${c.id}">Open member</button></td></tr>`}).join('')}</tbody></table></div></section>`;}
function loyaltyMember(id){const c=loyaltyMembers().find(c=>c.id===id);if(!c)return;openModal(c.name,`<div class="modal-body"><div class="store-facts"><span>Available points<strong>${c.points}</strong></span><span>Tier<strong>${memberTier(id)}</strong></span><span>Service credit<strong>${money(c.credit)}</strong></span><span>Member status<strong>${state.memberMeta[id].active?'Active':'Paused'}</strong></span></div><form data-loyalty-form="adjust" data-id="${id}"><h3>Correct a points balance</h3><div class="fields-two">${lf('delta','Points to add or deduct',0,-1000,1000)}<div class="field"><label for="adjust-reason">Reason</label><input id="adjust-reason" name="reason" maxlength="160" required></div></div><button class="btn secondary">Record adjustment</button><p class="error" data-loyalty-error></p></form><button class="text-btn" data-loyalty-action="member-status" data-id="${id}">${state.memberMeta[id].active?'Pause earning & redemption':'Resume membership'}</button><h3 style="margin-top:20px">Points ledger</h3>${ledgerRows(state.loyaltyLedger.filter(l=>l.customer===id).sort((a,b)=>b.date-a.date).slice(0,30))}</div>`);}
function ledgerRows(rows){return rows.map(l=>`<div class="audit-item"><div class="row between"><strong>${esc(l.reason)}</strong><span>${l.delta>=0?'+':''}${l.delta}</span></div><small>${dateText(l.date)} · Balance ${l.balance} · ${esc(l.type)}</small></div>`).join('')||'<p class="muted">No activity yet.</p>';}
function recoveryPage(storeId){const cases=state.recovery.filter(c=>!storeId?(ops.store==='all'||c.storeId===ops.store):c.storeId===storeId);return `<section class="card"><div class="section-head"><div><h2>Make a difficult visit right.</h2><p class="small muted">Store teams request compensation. HQ reviews the reason before issuing it.</p></div><button class="btn" data-loyalty-action="recovery-new">Request recovery</button></div>${cases.map(c=>{const member=loyaltyMembers().find(m=>m.id===c.customer),returned=state.orders.some(o=>o.customerId===c.customer&&!o.canceled&&stage(o)===4&&o.created>c.resolved);return `<article class="support-case"><div class="row between wrap"><h3>${esc(member?.name)} · ${esc(storeById(c.storeId).name)}</h3><span class="pill">${c.status}</span></div><p>${esc(c.reason)}</p><p><strong>${c.kind==='points'?c.amount+' points':money(c.amount)+' service credit'}</strong> · ${c.order||'General visit'}</p>${c.status==='Approved'?`<p class="small green">${returned?'A completed return purchase was observed.':'Waiting for a return visit.'}</p>`:''}${c.status==='Pending'&&!storeId?`<div class="row"><button class="btn secondary" data-loyalty-action="recovery-review" data-id="${c.id}">Review request</button></div>`:''}${c.decision?`<p class="small muted">HQ: ${esc(c.decision)}</p>`:''}</article>`}).join('')||'<p class="muted">No requests in this store scope.</p>'}</section>`;}
function recoveryForm(){const s=managerContext()?.store,stores=s?[s]:opsStores(),members=loyaltyMembers();openModal('Request guest recovery',`<form data-loyalty-form="recovery"><div class="modal-body"><div class="field"><label for="recovery-store">Store</label><select name="store" id="recovery-store">${stores.map(s=>`<option value="${s.id}">${esc(s.name)}</option>`).join('')}</select></div><div class="field"><label for="recovery-member">Member</label><select name="customer" id="recovery-member">${members.filter(c=>stores.some(s=>state.orders.some(o=>o.storeId===s.id&&o.customerId===c.id))).map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join('')}</select></div><div class="field"><label for="recovery-order">Order reference (optional)</label><input name="order" id="recovery-order" maxlength="60"></div><div class="fields-two"><div class="field"><label for="recovery-kind">Compensation</label><select name="kind" id="recovery-kind"><option value="points">Points</option><option value="credit">Service credit ($)</option></select></div>${lf('amount','Requested amount',25,1,500,.01)}</div><div class="field"><label for="recovery-reason">What happened?</label><textarea name="reason" id="recovery-reason" maxlength="300" required></textarea></div><p class="small muted">Up to 500 points or $50 credit per request. No funds are issued until HQ approval.</p><p class="error" data-loyalty-error></p></div><div class="modal-foot"><button class="btn full">Send to HQ for review</button></div></form>`);}
function recoveryReview(id){const c=state.recovery.find(c=>c.id===id);if(!c||c.status!=='Pending')return;openModal('Review guest recovery',`<form data-loyalty-form="decision" data-id="${id}"><div class="modal-body"><h3>${esc(loyaltyMembers().find(m=>m.id===c.customer)?.name)}</h3><p>${esc(c.reason)}</p><p class="notice">Approve to issue ${c.kind==='points'?c.amount+' points':money(c.amount)+' credit'} once to this member.</p><div class="field"><label for="recovery-decision">Decision</label><select name="decision" id="recovery-decision"><option>Approved</option><option>Rejected</option></select></div><div class="field"><label for="decision-note">Review note</label><textarea name="note" id="decision-note" maxlength="300" required></textarea></div><p class="error" data-loyalty-error></p></div><div class="modal-foot"><button class="btn full">Confirm decision</button></div></form>`);}
function loyaltyReport(){const rows=state.loyaltyLedger.filter(l=>l.date>=Date.now()-Number(ops.days)*DAY&&(ops.store==='all'||l.storeId===ops.store)),orders=scopedOrders().filter(o=>!o.canceled&&o.rewardId);return `<div class="metric-grid">${metricCard('Purchase points earned',rows.filter(l=>l.type==='earn').reduce((n,l)=>n+l.delta,0),'Selected store and period')}${metricCard('Reward orders',orders.length,'Non-canceled redemptions')}${metricCard('Reward discounts',money(orders.reduce((n,o)=>n+o.totals.discount,0)),'Discount value, not profit cost')}${metricCard('Pending recovery',state.recovery.filter(c=>c.status==='Pending'&&(ops.store==='all'||c.storeId===ops.store)).length,'Awaiting HQ review')}</div><section class="card"><h2>Points activity</h2><p class="small muted">Opening balances and HQ adjustments are network-wide; select All stores to include them. Balances are captured at the time of each event.</p>${ledgerRows(rows.slice(0,50))}</section>`;}
document.addEventListener('click',e=>{const tab=e.target.closest('[data-loyalty-tab]');if(tab){loyaltyTab=tab.dataset.loyaltyTab;render();return;}const b=e.target.closest('[data-loyalty-action]');if(!b)return;const a=b.dataset.loyaltyAction,id=b.dataset.id,hq=route().startsWith('admin');if(a==='recovery-new')return recoveryForm();if(!hq)return toast('This action belongs to HQ.');if(a==='edit-reward')rewardEditor(id);if(a==='member')loyaltyMember(id);if(a==='recovery-review')recoveryReview(id);if(a==='toggle-reward'){const r=state.rewardCatalog.find(r=>r.id===id);r.enabled=!r.enabled;log(`Reward ${r.name} ${r.enabled?'activated':'paused'}`,null);save();render();}if(a==='member-status'){state.memberMeta[id].active=!state.memberMeta[id].active;log(`Membership ${id} ${state.memberMeta[id].active?'resumed':'paused'}`,null);save();closeModal();render();}});
document.addEventListener('change',e=>{if(e.target.id==='loyalty-segment'){memberSegment=e.target.value;render();}if(e.target.id==='loyalty-search'){memberSearch=e.target.value;render();}});
document.addEventListener('submit',e=>{const f=e.target,kind=f.dataset.loyaltyForm;if(!kind)return;e.preventDefault();const d=new FormData(f),num=k=>Number(d.get(k)),fail=m=>{f.querySelector('[data-loyalty-error]').textContent=m;},hq=route().startsWith('admin');if(kind!=='recovery'&&!hq)return fail('HQ access is required.');try{
 if(kind==='program'){if(num('gold')<=num('silver'))return fail('Gold spend must be higher than Silver.');if(num('goldMultiplier')<num('silverMultiplier'))return fail('Gold multiplier must be at least Silver.');state.loyalty={rate:num('rate'),dailyCap:num('dailyCap'),tiers:d.has('tiers'),silver:Math.round(num('silver')*100),gold:Math.round(num('gold')*100),silverMultiplier:num('silverMultiplier'),goldMultiplier:num('goldMultiplier')};log('HQ updated loyalty earning rules',null);}
 if(kind==='reward'){const stores=d.getAll('stores'),type=d.get('kind');if(!stores.length)return fail('Select at least one store.');if(d.get('start')&&d.get('end')&&d.get('end')<d.get('start'))return fail('End date must follow start date.');if(type!=='delivery'&&(num('value')<=0||type==='percent'&&num('value')>100))return fail('Enter a positive value; percentages cannot exceed 100.');if(type==='item'&&d.get('item')&&d.get('category')&&product(d.get('item'))?.category!==d.get('category'))return fail('The item must belong to the selected category.');const existing=state.rewardCatalog.find(r=>r.id===f.dataset.id),r={id:existing?.id||uid(),name:d.get('name').trim(),desc:d.get('desc').trim(),points:num('points'),kind:type,value:type==='percent'?num('value'):Math.round(num('value')*100),min:Math.round(num('min')*100),item:d.get('item'),category:d.get('category'),tier:d.get('tier'),start:d.get('start'),end:d.get('end'),limit:num('limit'),stores,enabled:d.has('enabled'),image:existing?.image||d.get('item')||'custom'};if(!r.name||!r.desc)return fail('Add a name and description.');if(existing)Object.assign(existing,r);else state.rewardCatalog.push(r);log(`HQ saved reward ${r.name}`,null);}
 if(kind==='adjust'){const delta=num('delta'),reason=d.get('reason').trim();if(!Number.isInteger(delta)||!delta||Math.abs(delta)>1000||!reason)return fail('Enter 1–1,000 points to add or deduct and a reason.');pointEntry(f.dataset.id,delta,'adjustment',reason);log(`HQ adjusted ${f.dataset.id} by ${delta} points: ${reason}`,null);}
 if(kind==='recovery'){const sid=d.get('store'),customer=d.get('customer'),m=managerContext(),order=d.get('order').trim(),type=d.get('kind'),amount=type==='credit'?Math.round(num('amount')*100):num('amount');if(m&&sid!==m.store.id)return fail('Choose your own store.');if(!state.orders.some(o=>o.storeId===sid&&o.customerId===customer))return fail('This member has no order at the selected store.');if(order&&!state.orders.some(o=>o.id===order&&o.customerId===customer&&o.storeId===sid))return fail('Order must match this member and store.');if(!Number.isInteger(amount)||amount<=0||amount>(type==='credit'?5000:500))return fail('Maximum 500 whole points or $50 credit.');if(!d.get('reason').trim())return fail('Explain what happened.');if(order&&state.recovery.some(c=>c.order===order&&c.status!=='Rejected'))return fail('A recovery request already exists for this order.');state.recovery.unshift({id:uid(),storeId:sid,customer,order,kind:type,amount,reason:d.get('reason').trim(),status:'Pending',date:Date.now()});log(`Recovery requested for ${customer}`,sid);}
 if(kind==='decision'){const c=state.recovery.find(c=>c.id===f.dataset.id);if(!c||c.status!=='Pending')return fail('This request has already been reviewed.');const note=d.get('note').trim();if(!note)return fail('Add a review note.');c.status=d.get('decision');c.decision=note;c.resolved=Date.now();if(c.status==='Approved'){if(c.kind==='points')pointEntry(c.customer,c.amount,'recovery',`Recovery: ${c.reason}`,c.storeId);else {memberBalance(c.customer).credit+=c.amount;if(c.customer==='alex')state.ledger.unshift({id:uid(),title:'Recovery credit approved',detail:`+${money(c.amount)} · ${c.reason}`,date:Date.now()});}}log(`HQ ${c.status.toLowerCase()} recovery for ${c.customer}`,c.storeId);}
 save();if(modal.open)closeModal();render();toast(kind==='recovery'?'Request sent to HQ.':'Saved. Connected views are updated.');
 }catch(err){fail(err.message);}
});

function checkoutPointsEstimate(){const used=state.loyaltyLedger.filter(l=>l.customer==='alex'&&l.type==='earn'&&new Date(l.date).toDateString()===new Date().toDateString()).reduce((n,l)=>n+l.delta,0);return Math.min(earnEstimate({totals:totals(),customerId:'alex'}),Math.max(0,state.loyalty.dailyCap-used));}

function storeRewardSummary(id){return `<details class="card" style="margin:18px 0"><summary>Reward rules at this store</summary>${state.rewardCatalog.filter(r=>r.stores.includes(id)).map(r=>`<div class="audit-item"><strong>${esc(r.name)}</strong><p>${r.points} points · ${r.enabled?'Active':'Paused'} · Minimum ${money(r.min)} · ${r.tier} tier${r.end?' · Until '+r.end:''}</p></div>`).join('')}</details>`;}
