'use strict';

// Multi-store demo domain. Monetary amounts are integer cents; all locations and metrics are illustrative.
const DAY = 86400000;
const OPS_NAV = [['roadmap','grid','Features & roadmap'],['coupons','gift','Coupon management'],['campaign-results','grid','Campaign results'],['loyalty','gift','Loyalty administration'],['overview','grid','Overview'],['stores','pin','Stores'],['compare','grid','Compare stores'],['orders','orders','Orders'],['fulfillment','bike','Fulfillment'],['menu','pizza','Menu'],['customers','user','Customers'],['support','chat','Support'],['offers','gift','Offers'],['settings','settings','Settings'],['campaigns','gift','Campaigns'],['insights','grid','Guest insights']];
let ops = {store:'all',days:'7',mode:'All',status:'All',search:'',page:1,sort:'sales',compare:[]};
try{const saved=JSON.parse(sessionStorage.getItem('mod-operations-filters'));if(saved)ops={...ops,...saved};}catch{}

function initializeOperations(){
  if(!state.stores){
    const locations=[
      ['sea','Downtown Seattle','Seattle, WA','Pacific Northwest','Morgan Ellis','10:30','22:00',12,22],
      ['bel','Bellevue Square','Bellevue, WA','Pacific Northwest','Jordan Lee','10:30','21:00',10,18],
      ['por','Pearl District','Portland, OR','Pacific Northwest','Casey Rivera','11:00','22:00',9,20],
      ['aus','South Congress','Austin, TX','Central','Taylor Brooks','10:30','23:00',14,26],
      ['den','Cherry Creek','Denver, CO','Mountain','Sam Patel','11:00','21:30',8,16],
      ['phx','Arcadia','Phoenix, AZ','Southwest','Riley Chen','10:30','22:00',11,21]
    ];
    state.stores=locations.map((x,i)=>({id:x[0],name:i===0?state.store:x[1],city:x[2],region:x[3],manager:x[4],opens:x[5],closes:x[6],staff:x[7],capacity:x[8],paused:i===4,delivery:true,pickup:true,promo:i!==2,prep:15+i*2,deliveryFee:299+i*25,menu:structuredClone(i===0?state.menu:BASE_MENU.map(p=>({...p,available:true,price:p.price+(i%3)*50}))),address:`${100+i*140} Demo Avenue, ${x[2]}`}));
    state.stores[0].paused=state.paused;state.stores[0].promo=state.promo;
    state.customerStoreId='sea';
    state.customers=Array.from({length:24},(_,i)=>({id:`guest-${i+1}`,name:['Avery Williams','Jamie Nguyen','Chris Johnson','Priya Shah','Sofia Garcia','Drew Miller','Quinn Davis','Noah Wilson'][i%8]+(i>=8?' '+String.fromCharCode(65+Math.floor(i/8)):''),email:`sample${i+1}@example.com`,points:40+i*17,credit:(i%4)*250,gift:(i%5)*500}));
    state.orders.forEach(o=>{o.storeId='sea';o.customerId='alex';});
    const anchor=new Date();anchor.setHours(12,0,0,0);
    for(let day=0;day<30;day++)state.stores.forEach((store,si)=>{
      const quantity=3+(si*3+day)%5;
      for(let j=0;j<quantity;j++){
        const n=day*100+si*10+j,c=state.customers[(n+si)%24];
        const created=Math.min(Date.now()-600000,anchor.getTime()-day*DAY+(j-3)*3600000);
        const items=[store.menu[(n+1)%7],store.menu[(n+3)%7]].map((p,k)=>({uid:`sample-${n}-${k}`,id:p.id,image:p.id,name:p.name,qty:k===0?1+n%3:1,unit:p.price,options:p.category==='Pizzas'?{size:'Regular',crust:'Original',sauce:'Tomato',toppings:p.toppings}:null}));
        const subtotal=items.reduce((a,x)=>a+x.qty*x.unit,0),discount=n%7===0?Math.round(subtotal*.1):0,mode=n%3===0?'Pickup':'Delivery',delivery=mode==='Delivery'?store.deliveryFee:0,tax=Math.round((subtotal-discount)*.0875),tip=mode==='Delivery'?(n%4)*100:0,total=subtotal-discount+tax+delivery+tip;
        const canceled=n%19===0,progress=day===0&&j<3?((si+j)%4):4,prepMinutes=12+(n*7)%20,fulfillmentMinutes=mode==='Delivery'?prepMinutes+12+(n%16):prepMinutes;
        state.orders.push({id:`MOD-S${String(n+10000)}`,customerId:c.id,name:c.name,email:c.email,storeId:store.id,store:store.name,address:`${200+n%90} Example Street, ${store.city}`,mode,created,started:created,fixedStage:progress,canceled,earned:true,seed:true,items,totals:{subtotal,discount,tax,delivery,tip,total,credit:0,gift:0,due:total,pointsSpent:0},payment:'Demo card',prepMinutes,fulfillmentMinutes,promisedMinutes:mode==='Delivery'?40:22,completedAt:progress===4?created+fulfillmentMinutes*60000:null,channel:n%2?'Mobile web':'Desktop web',driver:mode==='Delivery'?['Jamie R.','Robin C.','Alex T.'][n%3]:'Store team',events:[],instructions:n%5===0?'Please leave at the front desk.':''});
      }
    });
    // Customer history is deliberately separate from the network's other customers.
    const history=state.orders.filter(o=>o.fixedStage===4&&!o.canceled&&o.storeId==='sea').slice(0,5);
    history.forEach(o=>{o.customerId='alex';o.name=state.profile.name;o.email=state.profile.email;});
    state.orders.sort((a,b)=>b.created-a.created);
    state.stores.forEach((s,i)=>{
      const order=state.orders.find(o=>o.storeId===s.id&&o.seed&&o.customerId!=='alex');
      state.tickets.push({id:`case-${s.id}`,order:order.id,storeId:s.id,issue:['Delivery is late','Missing or incorrect item','Question about my order'][i%3],message:['The driver is later than the estimate. Can you check?','One topping was missing. Please help.','Can you confirm the pickup counter?'][i%3],date:Date.now()-(i+1)*3600000,status:i%3===0?'Resolved':'Open'});
    });
    state.audit.unshift({title:'Sample network loaded: six stores and 30 days of illustrative orders',date:Date.now()});
    if(state.ledger.length===1&&state.ledger[0].title==='Welcome to your demo wallet')state.ledger=[{id:uid(),title:'Opening gift funds',detail:`+${money(state.gift)} demo gift balance`,date:Date.now()-3*DAY},{id:uid(),title:'Welcome service credit',detail:`+${money(state.credit)} demo service credit`,date:Date.now()-2*DAY},{id:uid(),title:'Opening rewards balance',detail:`${state.points} demo points available`,date:Date.now()-DAY}];
    state.operationsVersion=1;
  }
  state.customerStoreId ||= state.stores[0].id;
  state.orders.forEach(o=>{o.storeId ||= state.stores.find(s=>s.name===o.store)?.id || state.customerStoreId;o.customerId ||= 'alex';});
  if(ops.store!=='all'&&!storeById(ops.store))ops.store='all';
  syncCustomerStore();
}
function storeById(id){return state.stores.find(s=>s.id===id);}
function customerStore(){return storeById(state.customerStoreId);}
function syncCustomerStore(){const s=customerStore();state.menu=s.menu;state.store=s.name;state.paused=s.paused;state.promo=s.promo;}
function myOrders(){return state.orders.filter(o=>o.customerId==='alex');}
function opsStores(){return state.stores.filter(s=>(ops.store==='all'||s.id===ops.store)&&(!ops.region||ops.region==='all'||s.region===ops.region));}
function opsCutoff(){const d=new Date();d.setHours(0,0,0,0);return d.getTime()-(Number(ops.days)-1)*DAY;}
function scopedOrders(store=ops.store){return state.orders.filter(o=>(store==='all'||o.storeId===store)&&(!ops.region||ops.region==='all'||storeById(o.storeId)?.region===ops.region)&&o.created>=opsCutoff()&&(ops.mode==='All'||o.mode===ops.mode));}
function orderSales(o){return Math.max(0,o.totals.subtotal-(o.totals.merchandiseDiscount??o.totals.discount));}
function orderStatus(o){return o.canceled?'Canceled':(o.mode==='Pickup'?['Confirmed','Preparing','In the oven','Ready for pickup','Collected']:STAGES)[stage(o)];}
function metrics(orders){const valid=orders.filter(o=>!o.canceled),done=valid.filter(o=>stage(o)===4),timed=done.filter(o=>Number.isFinite(o.fulfillmentMinutes));return {orders:orders.length,sales:valid.reduce((n,o)=>n+orderSales(o),0),active:valid.filter(o=>stage(o)<4).length,completed:done.length,canceled:orders.length-valid.length,delivery:valid.filter(o=>o.mode==='Delivery').length,pickup:valid.filter(o=>o.mode==='Pickup').length,avg:valid.length?Math.round(valid.reduce((n,o)=>n+orderSales(o),0)/valid.length):0,ontime:timed.length?Math.round(timed.filter(o=>o.fulfillmentMinutes<=o.promisedMinutes).length/timed.length*100):null,prep:timed.length?Math.round(timed.reduce((n,o)=>n+o.prepMinutes,0)/timed.length):null,refund:orders.filter(o=>o.canceled).reduce((n,o)=>n+o.totals.total,0)};}
function metricCard(label,value,note){return `<div class="metric"><p>${label}</p><strong>${value}</strong><span>${note}</span></div>`;}
function opsToolbar(){const config=['menu','offers','settings','campaigns','coupons'].includes(route().split('/')[1])||(route()==='admin/loyalty'&&loyaltyTab!=='report');return `<section class="ops-toolbar" aria-label="Operations filters">${!config?`<label>Region<select id="ops-region"><option value="all">All regions</option>${[...new Set(state.stores.map(s=>s.region))].map(r=>`<option ${ops.region===r?'selected':''}>${r}</option>`).join('')}</select></label>`:''}<label>Store<select id="ops-store"><option value="all">All stores · Network</option>${state.stores.map(s=>`<option value="${s.id}" ${ops.store===s.id?'selected':''}>${esc(s.name)} · ${esc(s.city)}</option>`).join('')}</select></label>${config?'<p class="small muted">Current store configuration · historical reporting filters do not apply.</p>':`<label>Period<select id="ops-days">${[['1','Today'],['7','Last 7 days'],['30','Last 30 days']].map(([v,n])=>`<option value="${v}" ${ops.days===v?'selected':''}>${n}</option>`).join('')}</select></label><label>Fulfillment<select id="ops-mode">${['All','Delivery','Pickup'].map(x=>`<option ${ops.mode===x?'selected':''}>${x}</option>`).join('')}</select></label><button class="btn secondary" data-action="ops-export">${icon('orders')} Export orders CSV</button>`}</section>`;}
function operationsShell(){try{sessionStorage.setItem('mod-operations-filters',JSON.stringify(ops));}catch{}const section=route().split('/')[1]||'overview';return `<div class="topline">HQ WORKSPACE · MOD NETWORK</div><div class="admin-shell"><aside class="admin-sidebar"><button class="icon-btn staff-nav-close" data-staff-menu aria-label="Close navigation">${icon('close')}</button><a href="#admin">${brand()}</a><nav aria-label="Administration">${operationsNavigation(section)}</nav><button class="back-store" data-action="workspace-picker">↔ Switch workspace</button></aside><main id="main" class="admin-main">${staffConsole('hq')}<div class="admin-heading"><div><div class="eyebrow red">${ops.store==='all'?'NETWORK OPERATIONS':esc(storeById(ops.store).region)}</div><h1>${{roadmap:'Product direction.',coupons:'Every code. Clear rules.','campaign-results':'See how offers perform.',loyalty:'Loyalty that brings people back.',overview:'Network overview',stores:'Store directory',compare:'Store comparison',orders:'Order management',fulfillment:'From oven to doorstep.',menu:'Local menus. One standard.',customers:'Know your regulars.',support:'Make every visit right.',offers:'More reasons to MOD.',settings:'The details that deliver.',campaigns:'More reasons to return.',insights:'Know what brings them back.'}[section]||'Operations'}</h1><p class="muted small">${ops.store==='all'?'All 6 sample locations':esc(storeById(ops.store).name)} · USD · Illustrative operational data</p></div><span class="pill green">${state.stores.filter(s=>!s.paused).length} / ${state.stores.length} accepting orders</span></div>${section==='roadmap'||section==='loyalty'&&loyaltyTab==='program'?'':opsToolbar()}${operationsPage(section)}<p class="ops-footnote">Sample locations and operating data, not actual MOD performance. Dates use your browser’s timezone. Recorded sample queues advance with the controls; newly placed orders use the live demo clock.</p></main></div>`;}
function operationsPage(page){
  if(page==='roadmap')return stakeholderPage();
  if(page==='coupons')return couponAdmin();
  if(page==='campaign-results')return campaignResults();
  if(page==='loyalty')return loyaltyAdmin();
  if(page==='overview')return overviewPage();
  if(page==='campaigns')return hqCampaigns();
  if(page==='insights')return hqInsights();
  if(page==='stores')return storesPage();
  if(page==='compare')return comparePage();
  if(page==='orders')return `<section class="card"><div class="row between wrap"><h2>Order management</h2><span class="pill">${scopedOrders().length} orders in scope</span></div>${ordersControls()}<div id="ops-order-results">${operationsOrders()}</div></section>`;
  if(page==='fulfillment')return fulfillmentPage();
  if(page==='menu')return storeMenuPage();
  if(page==='customers')return customersPage();
  if(page==='support')return supportPage();
  if(page==='offers')return storeOffersPage();
  if(page==='settings')return storeSettingsPage();
  return `<section class="card"><h2>Page not found</h2><a class="btn" href="#admin">Back to overview</a></section>`;
}
function overviewPage(){const orders=scopedOrders(),m=metrics(orders);return `<div class="metric-grid">${metricCard('Net merchandise sales',money(m.sales),'Excludes tax, fees, tips and canceled orders')}${metricCard('Orders received',m.orders,`${m.completed} completed · ${m.canceled} canceled`)}${metricCard('Average order value',money(m.avg),'Net merchandise / non-canceled orders')}${metricCard('On-time fulfillment',m.ontime===null?'—':m.ontime+'%','Completed orders with recorded timing')}</div><div class="ops-two"><section class="card"><div class="row between wrap"><h2>Sales, day by day</h2><span class="pill">${ops.days==='1'?'Today':`${ops.days} days`}</span></div>${salesChart(orders)}<p class="small muted">Net merchandise sales · select a store above to drill down.</p></section><section class="card"><h2>Fulfillment mix</h2>${mixRow('Delivery',m.delivery,m.delivery+m.pickup)}${mixRow('Pickup',m.pickup,m.delivery+m.pickup)}<div class="summary-row"><span>In progress</span><strong>${m.active}</strong></div><div class="summary-row"><span>Average preparation</span><strong>${m.prep===null?'—':m.prep+' min'}</strong></div><a class="text-btn" href="#admin/fulfillment">Open fulfillment board →</a></section></div><section class="card"><div class="row between wrap"><h2>Store performance</h2><a href="#admin/compare" class="text-btn">Compare stores →</a></div>${storeTable(opsStores())}</section><div class="ops-two"><section class="card"><h2>Needs attention</h2>${opsStores().filter(s=>s.paused).map(s=>`<div class="audit-item"><span class="pill red">Ordering paused</span><p>${esc(s.name)}</p><button class="text-btn" data-action="ops-settings" data-id="${s.id}">Review store settings →</button></div>`).join('')}${opsStores().map(s=>{const n=scopedOrders(s.id).filter(o=>!o.canceled&&stage(o)<4&&isLate(o)).length;return n?`<div class="audit-item"><strong>${n} delayed orders</strong><p class="small muted">${esc(s.name)} · recorded service target exceeded</p><button class="text-btn" data-action="ops-queue" data-id="${s.id}">Inspect queue →</button></div>`:'';}).join('')}<p class="small muted" style="margin-top:12px">${scopedTickets().filter(t=>t.status==='Open').length} open support cases in the selected period.</p><a class="text-btn" href="#admin/support">Review support →</a></section><section class="card"><h2>Recent changes</h2>${state.audit.filter(a=>!a.storeId||ops.store==='all'||a.storeId===ops.store).slice(0,6).map(a=>`<div class="audit-item">${esc(a.title)}<small>${dateText(a.date)}</small></div>`).join('')}</section></div>`;}
function mixRow(label,n,total){return `<div class="mix-row"><div class="row between"><span>${label}</span><strong>${n} <small class="muted">(${total?Math.round(n/total*100):0}%)</small></strong></div><div class="mix-track"><i style="width:${total?n/total*100:0}%"></i></div></div>`;}
function salesChart(orders){const num=Number(ops.days),today=new Date();today.setHours(0,0,0,0);const bars=Array.from({length:num},(_,i)=>{const start=today.getTime()-(num-1-i)*DAY;return {date:new Date(start),value:orders.filter(o=>!o.canceled&&o.created>=start&&o.created<start+DAY).reduce((n,o)=>n+orderSales(o),0)};});const max=Math.max(1,...bars.map(x=>x.value));return `<div class="sales-chart" role="img" aria-label="Daily net sales: ${bars.map(b=>b.date.toLocaleDateString('en-US',{month:'short',day:'numeric'})+' '+money(b.value)).join('; ')}">${bars.map((b,i)=>`<div class="sales-bar" title="${b.date.toLocaleDateString()}: ${money(b.value)}"><span style="height:${Math.max(2,b.value/max*135)}px"></span><small>${num<=7||i%5===0?b.date.toLocaleDateString('en-US',{month:'numeric',day:'numeric'}):'·'}</small></div>`).join('')}</div>`;}
function storeTable(stores){const rows=stores.map(s=>({s,m:metrics(scopedOrders(s.id))})).sort((a,b)=>ops.sort==='name'?a.s.name.localeCompare(b.s.name):ops.sort==='ontime'?(b.m.ontime??-1)-(a.m.ontime??-1):b.m[ops.sort]-a.m[ops.sort]);return `<div class="admin-table-wrap"><table class="admin-table"><thead><tr><th>Store</th><th>Net sales</th><th>Orders</th><th>Avg. order</th><th>Delivery / pickup</th><th>On time</th><th>Active</th><th>Canceled / refunded</th><th>Avg. prep</th><th>Details</th></tr></thead><tbody>${rows.map(({s,m})=>`<tr><td><strong>${esc(s.name)}</strong><br><small class="muted">${esc(s.city)} · ${s.paused?'Paused':'Accepting orders'}</small></td><td>${money(m.sales)}</td><td>${m.orders}</td><td>${money(m.avg)}</td><td>${m.delivery} / ${m.pickup}</td><td><span class="pill ${m.ontime!==null&&m.ontime<80?'red':'green'}">${m.ontime===null?'—':m.ontime+'%'}</span></td><td>${m.active}</td><td>${m.canceled} / ${money(m.refund)}</td><td>${m.prep===null?'—':m.prep+' min'}</td><td><button class="text-btn" data-action="ops-store-detail" data-id="${s.id}">View store</button></td></tr>`).join('')}</tbody></table></div>`;}
function storesPage(){return `<p class="notice">These six locations represent an illustrative MOD network. Store-level changes affect only the selected location; the customer storefront chooses its own store.</p><div class="store-grid">${opsStores().map(s=>{const m=metrics(scopedOrders(s.id));return `<section class="card store-card"><div class="row between"><span class="store-symbol">${icon('pin')}</span><span class="pill ${s.paused?'red':'green'}">${s.paused?'Paused':'Accepting orders'}</span></div><h2>${esc(s.name)}</h2><p class="muted small">${esc(s.city)} · ${esc(s.region)}</p><div class="store-facts"><span>Manager<strong>${esc(s.manager)}</strong></span><span>Hours (local)<strong>${s.opens}–${s.closes}</strong></span><span>Net sales<strong>${money(m.sales)}</strong></span><span>Orders / active<strong>${m.orders} / ${m.active}</strong></span></div><div class="row wrap"><button class="btn secondary" data-action="ops-store-detail" data-id="${s.id}">Store details</button><button class="text-btn" data-action="ops-drill" data-id="${s.id}">View dashboard →</button></div></section>`;}).join('')}</div>`;}
function comparePage(){const choices=opsStores(),selected=choices.filter(s=>!ops.compare.length||ops.compare.includes(s.id));return `<section class="card"><div class="row between wrap"><div><h2>Compare what matters</h2><p class="small muted">Same period, same fulfillment filter, consistent sales definitions.</p></div><label class="ops-sort">Sort by<select id="ops-sort">${[['sales','Net sales'],['orders','Order count'],['ontime','On-time rate'],['name','Store name']].map(([id,t])=>`<option value="${id}" ${ops.sort===id?'selected':''}>${t}</option>`).join('')}</select></label></div><div class="compare-picks">${choices.map(s=>`<label><input type="checkbox" data-compare="${s.id}" ${!ops.compare.length||ops.compare.includes(s.id)?'checked':''}>${esc(s.name)}</label>`).join('')}</div>${storeTable(selected)}<p class="small muted" style="margin-top:15px">At least one store must remain selected. Choose “All stores” in the global filter for network comparisons.</p></section><div class="ops-two"><section class="card"><h2>Net sales by store</h2>${comparisonBars(selected,'sales')}</section><section class="card"><h2>On-time fulfillment</h2>${comparisonBars(selected,'ontime')}</section></div><section class="card"><h3>How to read these numbers</h3><p class="small muted" style="margin-top:8px">Net sales are food subtotal less discounts, excluding canceled orders, tax, delivery fees and tips. Order count includes cancellations. Average order value uses non-canceled orders. On-time rate uses completed orders with a recorded fulfillment duration and compares that duration with the promised time. No timing data displays as “—”, not zero.</p></section>`;}
function comparisonBars(stores,key){const rows=stores.map(s=>({s,m:metrics(scopedOrders(s.id))})),max=key==='ontime'?100:Math.max(1,...rows.map(x=>x.m.sales));return rows.sort((a,b)=>(b.m[key]??-1)-(a.m[key]??-1)).map(({s,m})=>`<div class="mix-row"><div class="row between"><button class="text-btn" data-action="ops-drill" data-id="${s.id}">${esc(s.name)}</button><strong>${key==='sales'?money(m[key]):m[key]===null?'—':m[key]+'%'}</strong></div><div class="mix-track"><i style="width:${(m[key]||0)/max*100}%"></i></div></div>`).join('');}
function ordersControls(){return `<div class="order-filters"><label class="searchbox">${icon('search')}<input id="ops-search" aria-label="Search orders" placeholder="Order ID, customer or store" value="${esc(ops.search)}"></label><label>Status<select id="ops-status">${['All','Active','Completed','Canceled','Delayed'].map(s=>`<option ${ops.status===s?'selected':''}>${s}</option>`).join('')}</select></label><button class="text-btn" data-action="ops-clear">Clear filters</button></div>`;}
function isLate(o){return o.fixedStage!==undefined?o.fulfillmentMinutes>o.promisedMinutes:elapsed(o)>150;}
function filteredOpsOrders(){return scopedOrders().filter(o=>(ops.status==='All'||ops.status==='Active'&&!o.canceled&&stage(o)<4||ops.status==='Completed'&&stage(o)===4||ops.status==='Canceled'&&o.canceled||ops.status==='Delayed'&&!o.canceled&&stage(o)<4&&isLate(o))&&`${o.id} ${o.name} ${o.store}`.toLowerCase().includes(ops.search.toLowerCase()));}
function operationsOrders(){const all=filteredOpsOrders(),pages=Math.max(1,Math.ceil(all.length/12));ops.page=Math.min(ops.page,pages);const orders=all.slice((ops.page-1)*12,ops.page*12);return `<div class="admin-table-wrap"><table class="admin-table"><thead><tr><th>Order / store</th><th>Customer</th><th>Total paid</th><th>Fulfillment</th><th>Status</th><th>Actions</th></tr></thead><tbody>${orders.map(o=>`<tr><td><strong>${o.id}</strong><br><small>${esc(o.store)}</small><br><small class="muted">${dateText(o.created)}</small></td><td>${esc(o.name)}<br><small class="muted">${o.items.reduce((n,x)=>n+x.qty,0)} items · ${o.channel||'Web'}</small></td><td>${money(o.totals.total)}</td><td>${o.mode}${!o.canceled&&stage(o)<4&&isLate(o)?'<br><span class="pill red">Delayed</span>':''}</td><td><span class="pill ${o.canceled?'red':stage(o)===4?'green':''}">${orderStatus(o)}</span></td><td><div class="row"><button class="text-btn" data-action="ops-order" data-id="${o.id}">Details</button>${!o.canceled&&stage(o)<4?`<button class="text-btn" data-action="advance" data-id="${o.id}">Advance</button>`:''}</div></td></tr>`).join('')||'<tr><td colspan="6">No orders match these filters. Clear filters or choose a wider period.</td></tr>'}</tbody></table></div><div class="pagination"><span>${all.length} results · Page ${ops.page} of ${pages}</span><div class="row"><button class="btn secondary" data-action="ops-prev" ${ops.page===1?'disabled':''}>Previous</button><button class="btn secondary" data-action="ops-next" ${ops.page===pages?'disabled':''}>Next</button></div></div>`;}
function fulfillmentPage(){const orders=scopedOrders().filter(o=>!o.canceled&&stage(o)<4),late=orders.filter(isLate);return `<div class="metric-grid">${metricCard('Active orders',orders.length,'Selected stores and period')}${metricCard('Needs attention',late.length,'Beyond the illustrative service target')}${metricCard('In kitchen',orders.filter(o=>stage(o)<3).length,'Confirmed, preparing or in oven')}${metricCard('Dispatched / ready',orders.filter(o=>stage(o)===3).length,'Delivery on the way or pickup ready')}</div><div class="fulfillment-board">${[0,1,2,3].map(n=>`<section class="queue-column"><div class="row between"><h3>${['New orders','Preparing','In the oven','On the way / ready'][n]}</h3><span class="pill">${orders.filter(o=>stage(o)===n).length}</span></div>${orders.filter(o=>stage(o)===n).map(o=>`<article class="queue-card"><div class="row between"><strong>${o.id}</strong><span class="pill ${isLate(o)?'red':''}">${isLate(o)?'Delayed':o.mode}</span></div><p>${esc(o.store)}</p>${o.group?`<span class="pill green">Group · ${o.group.people.length} people</span>`:''}<p class="small muted">${esc(o.name)} · ${o.items.reduce((a,x)=>a+x.qty,0)} items</p><p class="small">${o.mode==='Delivery'?esc(o.driver||'Jamie R.'):'Pickup counter'} · ${money(o.totals.total)}</p><div class="row wrap"><button class="text-btn" data-action="ops-order" data-id="${o.id}">Details</button><button class="btn secondary" data-action="advance" data-id="${o.id}">${n===3?(o.mode==='Pickup'?'Collected':'Delivered'):'Next stage'}</button></div></article>`).join('')||'<p class="small muted">Queue clear.</p>'}</section>`).join('')}</div>`;}
function scopedTickets(){return state.tickets.filter(t=>(ops.store==='all'||(t.storeId||orderById(t.order)?.storeId)===ops.store)&&t.date>=opsCutoff()&&(ops.mode==='All'||orderById(t.order)?.mode===ops.mode));}
function supportPage(){const tickets=scopedTickets();return `<section class="card"><div class="row between wrap"><h2>Support inbox</h2><span class="pill">${tickets.filter(t=>t.status==='Open').length} open · ${tickets.length} total</span></div>${tickets.map(t=>`<article class="support-case"><div class="row between wrap"><h3>${esc(t.issue)}</h3><span class="pill ${t.status==='Open'?'red':'green'}">${t.status}</span></div><p class="small muted">${esc(t.order)} · ${esc(orderById(t.order)?.store||'Store')} · ${dateText(t.date)}</p><p>${esc(t.message)}</p><div class="row wrap"><button class="text-btn" data-action="ops-order" data-id="${t.order}">Order details</button>${t.status==='Open'?`<button class="btn secondary" data-action="resolve-ticket" data-id="${t.id}">Mark resolved</button>`:'<span class="small green">Resolved in demo inbox</span>'}</div></article>`).join('')||'<p class="muted" style="padding:24px 0">No support cases match this scope.</p>'}</section>`;}
function requireStore(message){return `<section class="card"><h2>Select a store to edit</h2><p class="muted" style="margin:15px 0">${message} Choose a location above, or open one below.</p><div class="compare-picks">${state.stores.map(s=>`<button class="btn secondary" data-action="ops-select" data-id="${s.id}">${esc(s.name)}</button>`).join('')}</div></section>`;}
function storeMenuPage(){if(ops.store==='all')return requireStore('Prices and item availability belong to individual stores.');const s=storeById(ops.store);return `<p class="notice">Editing ${esc(s.name)} only. Existing orders retain their original prices. The storefront reflects changes when this store is selected.</p><div class="staff-menu-filter">${staffMenuFilter()}</div><div class="menu-admin-grid">${s.menu.filter(p=>staffMenuCategory==='All'||p.category===staffMenuCategory).map(p=>`<form class="admin-product" data-ops-form="menu" data-id="${p.id}" data-store="${s.id}"><img src="${menuImage(p.id)}" alt="${esc(p.name)}"><div class="grow"><h3>${esc(p.name)}</h3><p class="small muted">${p.category}</p><div class="row wrap"><div class="field"><label for="ops-price-${p.id}">Price (USD)</label><input id="ops-price-${p.id}" type="number" name="price" min="0" max="99" step=".01" required value="${(p.price/100).toFixed(2)}"></div><label class="switch"><input name="available" type="checkbox" ${p.available?'checked':''}>Available</label></div><button class="text-btn" type="submit">Save item</button></div></form>`).join('')}</div>`;}
function customersPage(){const orders=scopedOrders(),ids=new Set(orders.map(o=>o.customerId));const customers=[{id:'alex',...state.profile,points:state.points,gift:state.gift,credit:state.credit},...state.customers].filter(c=>ids.has(c.id)||c.id==='alex');return `<section class="card"><h2>Customers in this scope</h2><p class="small muted">Customers with orders in the selected period, plus the signed-in demo profile. Wallet balances are customer-wide.</p><div class="admin-table-wrap"><table class="admin-table"><thead><tr><th>Customer</th><th>Orders in scope</th><th>Net spend</th><th>Points</th><th>Service credit</th><th>Profile</th></tr></thead><tbody>${customers.map(c=>{const m=metrics(orders.filter(o=>o.customerId===c.id));return `<tr><td><strong>${esc(c.name)}</strong><br><small>${esc(c.email)}</small></td><td>${m.orders}</td><td>${money(m.sales)}</td><td>${c.points}</td><td>${money(c.credit)}</td><td><button class="text-btn" data-action="ops-customer" data-id="${c.id}">View customer</button></td></tr>`;}).join('')}</tbody></table></div></section>`;}
function storeOffersPage(){return `<section class="card"><h2>MOD10 · A little extra love</h2><p style="margin:15px 0">10% off merchandise. Cannot combine with a points reward.</p><p class="small muted">Enable or disable the offer per location. These are prototype rules, not official MOD offers.</p>${opsStores().map(s=>`<div class="summary-row"><div><strong>${esc(s.name)}</strong><p class="small muted">${esc(s.city)}</p></div><label class="switch"><input type="checkbox" data-store-promo="${s.id}" ${s.promo?'checked':''}>Enabled</label></div>`).join('')}<a href="#rewards" class="text-btn">Preview customer rewards →</a></section>`;}
function storeSettingsPage(){if(ops.store==='all')return requireStore('Hours, staffing, fulfillment and order acceptance are managed per location.');const s=storeById(ops.store);return `<form class="card" data-ops-form="settings" data-store="${s.id}"><h2>${esc(s.name)}</h2><div class="fields-two">${[['name','Store name',s.name,'text'],['manager','Manager',s.manager,'text'],['opens','Opens (store local time)',s.opens,'time'],['closes','Closes (store local time)',s.closes,'time'],['staff','Scheduled team members',s.staff,'number'],['capacity','Orders per 15 minutes',s.capacity,'number'],['prep','Quoted preparation minutes',s.prep,'number'],['deliveryFee','Delivery fee (USD)',(s.deliveryFee/100).toFixed(2),'number']].map(([name,label,value,type])=>`<div class="field"><label for="setting-${name}">${label}</label><input id="setting-${name}" name="${name}" type="${type}" required maxlength="70" ${type==='number'?`min="${name==='deliveryFee'?0:1}" max="${name==='prep'?120:99}" step="${name==='deliveryFee'?'.01':'1'}"`:''} value="${esc(value)}"></div>`).join('')}</div><div class="compare-picks"><label><input type="checkbox" name="paused" ${s.paused?'checked':''}>Pause new orders</label><label><input type="checkbox" name="delivery" ${s.delivery?'checked':''}>Delivery enabled</label><label><input type="checkbox" name="pickup" ${s.pickup?'checked':''}>Pickup enabled</label></div><p class="notice">Hours, staffing and capacity are planning fields in this prototype. Pausing, fulfillment switches, prep estimate and delivery fee affect checkout. Hours do not automatically open or close a store.</p><button class="btn" type="submit" style="margin-top:20px">Save store settings</button></form><section class="card" style="margin-top:20px"><h3>Demo controls</h3><div class="row wrap" style="margin-top:15px"><button class="btn secondary" data-action="new-demo">Create customer delivery</button><button class="text-btn" data-action="reset">Reset all demo data</button></div></section>`;}
function storeDetail(id){const s=storeById(id),m=metrics(scopedOrders(id));openModal(esc(s.name),`<div class="modal-body"><span class="pill ${s.paused?'red':'green'}">${s.paused?'Ordering paused':'Accepting orders'}</span><p style="margin-top:15px">${esc(s.address)}</p><p class="small muted">Illustrative address · ${esc(s.region)}</p><div class="store-facts"><span>Store manager<strong>${esc(s.manager)}</strong></span><span>Local hours<strong>${s.opens}–${s.closes}</strong></span><span>Scheduled team<strong>${s.staff} people</strong></span><span>Capacity plan<strong>${s.capacity} orders / 15 min</strong></span><span>Net sales<strong>${money(m.sales)}</strong></span><span>On-time fulfillment<strong>${m.ontime===null?'—':m.ontime+'%'}</strong></span><span>Prep estimate<strong>${s.prep} min</strong></span><span>Delivery fee<strong>${money(s.deliveryFee)}</strong></span></div><div class="row wrap"><button class="btn" data-action="ops-drill" data-id="${id}">Store dashboard</button><button class="btn secondary" data-action="ops-settings" data-id="${id}">Edit settings</button><a class="text-btn" href="#store/${id}/today">Open manager workspace →</a></div></div>`);}
function operationsOrder(id){const o=orderById(id);if(!o)return toast('Order no longer exists.');openModal(`Order ${esc(o.id)}`,`<div class="modal-body"><div class="row between wrap"><h3>${esc(o.name)}</h3>${o.group?`<span class="pill green">Group · ${esc(o.group.name)}</span>`:''}<span class="pill">${orderStatus(o)}</span></div><p class="small muted">${esc(o.store)} · ${o.mode} · ${dateText(o.created)}</p><p class="small" style="margin-top:10px">${esc(o.address)}</p>${o.instructions?`<p class="notice">${esc(o.instructions)}</p>`:''}${o.items.map(x=>`<div class="summary-row"><span>${x.qty} × ${esc(x.name)}<br><small>${esc(itemDesc(x))}</small></span><strong>${money(x.unit*x.qty)}</strong></div>`).join('')}<div class="summary-row"><span>Discounts</span><span>−${money(o.totals.discount)}</span></div><div class="summary-row"><span>Tax / delivery / tip</span><span>${money(o.totals.tax)} / ${money(o.totals.delivery)} / ${money(o.totals.tip)}</span></div><div class="summary-row total"><span>Total ${o.canceled?'refunded':'paid'}</span><strong>${money(o.totals.total)}</strong></div><p class="small muted">${money(o.totals.gift)} gift funds · ${money(o.totals.credit)} service credit · ${money(o.totals.due)} ${esc(o.payment)}</p><h3 style="margin-top:22px">Fulfillment</h3><p class="small">${o.mode==='Delivery'?`Partner: ${esc(o.driver||'Jamie R.')}`:'Store pickup counter'} · ${o.fixedStage!==undefined?'Recorded sample snapshot':'Live demo clock'}</p>${o.prepMinutes?`<p class="small muted">Preparation ${o.prepMinutes} min · Total fulfillment ${o.fulfillmentMinutes} min · Promise ${o.promisedMinutes} min</p>`:''}<div class="row wrap" style="margin-top:18px">${!o.canceled&&stage(o)<4?`<button class="btn secondary" data-action="ops-advance-modal" data-id="${o.id}">Advance order</button>`:''}<button class="text-btn" data-action="ops-receipt" data-id="${o.id}">Full receipt</button></div><p class="notice" style="margin-top:15px">Full cancellation is simulated. Only this customer’s eligible funds and points are restored; other customers’ balances remain separate.</p></div><div class="modal-foot"><button class="btn full" data-action="cancel-order" data-id="${o.id}" ${o.canceled?'disabled':''}>${o.canceled?'Already canceled':'Cancel & refund demo order'}</button></div>`);}
function customerDetail(id){const c=id==='alex'?{id,...state.profile,points:state.points,credit:state.credit,gift:state.gift}:state.customers.find(c=>c.id===id);const m=metrics(scopedOrders().filter(o=>o.customerId===id));openModal(esc(c.name),`<div class="modal-body"><p class="small muted">${esc(c.email)} · ${id==='alex'?'Storefront profile':'Sample customer'}</p><div class="store-facts"><span>Orders in scope<strong>${m.orders}</strong></span><span>Net spend<strong>${money(m.sales)}</strong></span><span>Points<strong>${c.points}</strong></span><span>Gift funds<strong>${money(c.gift)}</strong></span><span>Service credit<strong>${money(c.credit)}</strong></span></div><form data-ops-form="credit" data-customer="${id}"><h3>Issue service credit</h3><div class="field"><label for="ops-credit">Amount (USD)</label><input id="ops-credit" type="number" name="amount" min="1" max="100" step=".01" required></div><div class="field"><label for="ops-reason">Reason</label><input id="ops-reason" name="reason" required maxlength="150"></div><button class="btn full" type="submit">Issue demo credit</button></form></div>`);}
function exportOperations(){const rows=[['Order','Store','Customer','Placed','Fulfillment','Status','Net merchandise USD','Tax USD','Delivery USD','Tip USD','Total USD'],...(route()==='admin/orders'?filteredOpsOrders():scopedOrders()).map(o=>[o.id,o.store,o.name,new Date(o.created).toISOString(),o.mode,orderStatus(o),(orderSales(o)/100).toFixed(2),(o.totals.tax/100).toFixed(2),(o.totals.delivery/100).toFixed(2),(o.totals.tip/100).toFixed(2),(o.totals.total/100).toFixed(2)])];const csv=rows.map(r=>r.map(v=>'"'+String(v).replace(/^[=+@-]/,"'$&").replaceAll('"','""')+'"').join(',')).join('\r\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8;'})),a=document.createElement('a');a.href=url;a.download=`mod-orders-${ops.store}-${ops.days}days.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast(`${rows.length-1} filtered orders exported.`);}

function commitCustomerStore(id){
  const s=storeById(id);if(!s)return;
  state.customerStoreId=id;syncCustomerStore();
  if(!s.delivery&&state.mode==='Delivery'&&s.pickup)state.mode='Pickup';
  if(!s.pickup&&state.mode==='Pickup'&&s.delivery)state.mode='Delivery';
  save();closeModal();render();toast(`${s.name} selected.${count()?' Your bag now uses this store’s prices.':''}`);
}
function customerLocationModal(){openModal('Choose your MOD',`<div class="modal-body"><p class="small muted">Sample locations · Select the store preparing your order. Existing bag items use the selected store’s prices and availability.</p><div class="customer-stores">${state.stores.map(s=>`<article class="customer-store ${s.id===state.customerStoreId?'selected':''}"><div class="row between wrap"><h3>${esc(s.name)}</h3><span class="pill ${s.paused?'red':'green'}">${s.paused?'Paused':s.id===state.customerStoreId?'Selected':'Accepting orders'}</span></div><p class="small muted">${esc(s.city)} · ${s.opens}–${s.closes} local</p><p class="small">${s.delivery?'Delivery · '+money(s.deliveryFee):'Delivery unavailable'} · ${s.pickup?'Pickup · '+s.prep+' min':'Pickup unavailable'}</p><button class="btn secondary" data-action="customer-store" data-id="${s.id}" ${s.id===state.customerStoreId?'disabled':''}>${s.id===state.customerStoreId?'Your store':'Select store'}</button></article>`).join('')}</div><button class="text-btn" data-action="edit-address">Edit delivery address & order type →</button></div>`);}
function walletTopup(){openModal('Add demo gift funds',`<form data-ops-form="topup"><div class="modal-body"><p class="notice">Prototype only. This adds sample funds; no payment is collected.</p><div class="field"><label for="topup-amount">Amount (USD)</label><select id="topup-amount" name="amount"><option value="1000">$10</option><option value="2500">$25</option><option value="5000">$50</option></select></div></div><div class="modal-foot"><button class="btn full" type="submit">Add demo funds</button></div></form>`);}
function walletGift(){openModal('Redeem a demo gift card',`<form data-ops-form="gift"><div class="modal-body"><p class="notice">Try MODGIFT25 for $25 in sample funds. Each browser can redeem it once. No real gift cards are accepted.</p><div class="field"><label for="gift-code">Demo gift code</label><input id="gift-code" name="code" required maxlength="30" autocomplete="off" placeholder="MODGIFT25"></div><p id="gift-error" role="alert" class="red small"></p></div><div class="modal-foot"><button class="btn full" type="submit">Redeem demo card</button></div></form>`);}

document.addEventListener('click',e=>{
  const el=e.target.closest('[data-action]');if(!el||el.disabled)return;const a=el.dataset.action,id=el.dataset.id;
  if(a==='customer-store')return chooseCustomerStore(id);
  if(a==='store-picker')return customerLocationModal();
  if(a==='edit-address'){closeModal();locationModal();return;}
  if(a==='wallet-topup')return walletTopup();
  if(a==='wallet-gift')return walletGift();
  if(a==='ops-select'||a==='ops-drill'||a==='ops-settings'||a==='ops-queue'){ops.store=id;ops.page=1;ops.compare=[];if(modal.open)closeModal();if(a==='ops-drill')navigate('admin');else if(a==='ops-settings')navigate('admin/settings');else if(a==='ops-queue')navigate('admin/fulfillment');else render();return;}
  if(a==='ops-store-detail')return storeDetail(id);
  if(a==='ops-order')return operationsOrder(id);
  if(a==='ops-customer')return customerDetail(id);
  if(a==='ops-advance-modal'){advanceOrder(orderById(id));closeModal();operationsOrder(id);return;}
  if(a==='ops-receipt'){closeModal();showReceipt(orderById(id));return;}
  if(a==='ops-export')return exportOperations();
  if(a==='ops-next'||a==='ops-prev'){ops.page+=a==='ops-next'?1:-1;render();return;}
  if(a==='ops-clear'){ops.search='';ops.status='All';ops.mode='All';ops.page=1;render();return;}
  if(a==='map-zoom'){const map=$('.map');const zoom=Number(el.dataset.zoom);map.setAttribute('viewBox',zoom===1?'100 80 480 360':'0 0 700 520');return;}
});
document.addEventListener('input',e=>{if(e.target.id==='ops-search'){ops.search=e.target.value;ops.page=1;$('#ops-order-results').innerHTML=operationsOrders();}});
document.addEventListener('change',e=>{
  const el=e.target;
  if(['ops-store','ops-days','ops-mode','ops-status','ops-sort'].includes(el.id)){ops[{'ops-store':'store','ops-days':'days','ops-mode':'mode','ops-status':'status','ops-sort':'sort'}[el.id]]=el.value;ops.page=1;if(el.id==='ops-store')ops.compare=[];render();return;}
  if(el.dataset.compare){const selected=$$('[data-compare]:checked').map(x=>x.dataset.compare);if(!selected.length){el.checked=true;toast('Keep at least one store selected.');return;}ops.compare=selected;render();return;}
  if(el.dataset.storePromo){const s=storeById(el.dataset.storePromo);s.promo=el.checked;syncCustomerStore();log(`${s.name}: MOD10 ${s.promo?'enabled':'disabled'}`,s.id);save();toast('Store offer updated.');}
});
document.addEventListener('submit',e=>{
  const f=e.target,kind=f.dataset.opsForm;if(!kind)return;e.preventDefault();const d=new FormData(f);
  if(kind==='menu'){const s=storeById(f.dataset.store),p=s.menu.find(p=>p.id===f.dataset.id),price=Math.round(Number(d.get('price'))*100);if(!Number.isFinite(price)||price<0||price>9900)return;p.price=price;p.available=d.has('available');syncCustomerStore();log(`${s.name}: ${p.name} ${money(price)} · ${p.available?'available':'sold out'}`,s.id);save();render();toast(`Menu saved for ${s.name}.`);}
  if(kind==='settings'){const s=storeById(f.dataset.store);if(!d.has('delivery')&&!d.has('pickup'))return toast('Enable delivery or pickup, or pause ordering.');for(const key of ['name','manager','opens','closes'])s[key]=d.get(key).trim();for(const key of ['staff','capacity','prep'])s[key]=Number(d.get(key));s.deliveryFee=Math.round(Number(d.get('deliveryFee'))*100);for(const key of ['paused','delivery','pickup'])s[key]=d.has(key);syncCustomerStore();log(`${s.name}: operating settings updated`,s.id);save();render();toast('Store settings saved.');}
  if(kind==='credit'){const id=f.dataset.customer,amount=Math.round(Number(d.get('amount'))*100),reason=d.get('reason').trim();if(!Number.isFinite(amount)||amount<100||amount>10000||!reason)return;const c=id==='alex'?state:state.customers.find(c=>c.id===id);c.credit+=amount;if(id==='alex')state.ledger.unshift({id:uid(),title:'Service credit issued',detail:`+${money(amount)} · ${reason}`,date:Date.now()});log(`Issued ${money(amount)} credit to ${id==='alex'?state.profile.name:c.name}: ${reason}`,ops.store==='all'?null:ops.store);save();closeModal();render();toast('Customer service credit updated.');}
  if(kind==='topup'||kind==='gift'){let amount=Number(d.get('amount'));if(kind==='gift'){if(d.get('code').trim().toUpperCase()!=='MODGIFT25'){$('#gift-error').textContent='Use the demo code MODGIFT25.';return;}if(state.giftRedeemed){$('#gift-error').textContent='This demo gift card has already been redeemed.';return;}amount=2500;state.giftRedeemed=true;}if(![1000,2500,5000].includes(amount))return;state.gift+=amount;state.ledger.unshift({id:uid(),title:kind==='gift'?'Demo gift card redeemed':'Demo funds added',detail:`+${money(amount)} gift funds · no charge`,date:Date.now()});save();closeModal();render();toast(`${money(amount)} demo gift funds added.`);}
});

function deliveryChat(id){const o=orderById(id);o.messages ||= [];openModal(o.mode==='Delivery'?'Delivery partner chat':'Store support chat',`<div class="modal-body"><div class="row"><span class="avatar">${o.mode==='Delivery'?'JR':'MOD'}</span><div><h3>${o.mode==='Delivery'?esc(o.driver||'Jamie R.'):esc(o.store)}</h3><p class="small muted">Local simulated conversation</p></div></div><div class="chat-thread"><p class="chat-bubble">${o.canceled?'Your order is canceled. Support can help with your next order.':stage(o)===4?'Your order is complete. How can we help?':'We have your order. Send any delivery or pickup instructions here.'}</p>${o.messages.map(m=>`<p class="chat-bubble ${m.from==='you'?'outgoing':''}"><small>${m.from==='you'?'You':'Demo support'}</small>${esc(m.text)}</p>`).join('')}</div><form data-ops-form="chat" data-order="${o.id}"><div class="field"><label for="chat-message">Message</label><input id="chat-message" name="message" required maxlength="300" placeholder="Please ring the doorbell"></div><button class="btn full" type="submit">Send demo message</button></form><p class="small muted" style="margin-top:15px">Messages stay in this browser; replies are automated. Nothing is sent to a real driver.</p><button class="text-btn" data-action="contact-support" data-id="${o.id}">Create a support case →</button></div>`);}
document.addEventListener('submit',e=>{const f=e.target;if(f.dataset.opsForm!=='chat')return;e.preventDefault();const text=new FormData(f).get('message').trim();if(!text)return;const o=orderById(f.dataset.order);o.messages.push({from:'you',text,date:Date.now()},{from:'support',text:'Thanks! Your message is saved in this demo conversation. For an issue that needs a response, create a support case below.',date:Date.now()});save();closeModal();deliveryChat(o.id);});
