'use strict';
const slotFormatters={};
function orderZone(storeId=state.customerStoreId){return {sea:'America/Los_Angeles',bel:'America/Los_Angeles',por:'America/Los_Angeles',aus:'America/Chicago',den:'America/Denver',phx:'America/Phoenix'}[storeId]||'America/Los_Angeles';}
function slotParts(t){return Object.fromEntries((slotFormatters[orderZone()] ||= new Intl.DateTimeFormat('en-CA',{timeZone:orderZone(),year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'})).formatToParts(t).map(p=>[p.type,p.value]));}
function slotDay(t){const p=slotParts(t);return `${p.year}-${p.month}-${p.day}`;}
function scheduleLabel(t,storeId=state.customerStoreId){return new Intl.DateTimeFormat('en-US',{timeZone:orderZone(storeId),weekday:'short',month:'short',day:'numeric',hour:'numeric',minute:'2-digit',timeZoneName:'short'}).format(t);}
function availableSlots(){const s=customerStore(),lead=Math.max(30,s.prep+(state.mode==='Delivery'?20:0)),first=Math.ceil((Date.now()+lead*60000)/1800000)*1800000;const minutes=v=>{const [h,m]=v.split(':').map(Number);return h*60+m;};return Array.from({length:7*48},(_,i)=>first+i*1800000).filter(t=>{const p=slotParts(t),m=Number(p.hour)*60+Number(p.minute);return m>=minutes(s.opens)&&m<=minutes(s.closes)-15;});}
function selectedTime(){return checkout.scheduledAt||state.fulfillmentAt||null;}
function orderControls(home=false){const t=selectedTime();return `<section class="order-launch ${home?'home-launch':''}" aria-label="Start your order"><div class="order-launch-top"><button class="launch-store" data-action="store-picker" aria-label="Change store">${icon('pin')}<span><small>YOUR STORE</small><strong>${esc(state.store)}</strong></span>${icon('chevron')}</button><button class="btn launch-group" data-fast-order="group">${icon('user')} Group order <span>→</span></button></div><div class="order-launch-bottom"><div class="segmented" aria-label="Order type">${['Pickup','Delivery'].map(m=>`<button data-action="mode" data-mode="${m}" class="${state.mode===m?'selected':''}" aria-pressed="${state.mode===m}">${m}</button>`).join('')}</div><div class="segmented" aria-label="Order timing"><button data-fast-order="now" class="${!t?'selected':''}" aria-pressed="${!t}">ASAP</button><button data-fast-order="later" class="${t?'selected':''}" aria-pressed="${!!t}">${icon('clock')} Later</button></div><button class="launch-time" data-fast-order="later">${t?scheduleLabel(t):`Ready ${state.mode==='Delivery'?'for delivery':'for pickup'} in ${customerStore().prep+(state.mode==='Delivery'?10:0)}–${customerStore().prep+(state.mode==='Delivery'?20:5)} min`} ${icon('chevron')}</button></div>${state.paused?'<p class="error" style="padding:0 18px">This store has paused orders. Choose another store to order.</p>':''}${home?`<div class="launch-actions"><button class="btn full" data-fast-order="order">${t?'Order for later':'Order now'} ${icon('chevron')}</button></div>`:''}</section>`;}
let scheduleDate='';
function schedulePicker(){const slots=availableSlots(),days=[...new Set(slots.map(slotDay))],current=selectedTime();scheduleDate=current&&days.includes(slotDay(current))?slotDay(current):days[0];openModal('Schedule your order',`<form data-ordering-form="schedule"><div class="modal-body"><p class="schedule-store">${esc(state.store)} · ${state.mode}</p><div class="field"><label for="schedule-day">Day</label><select id="schedule-day">${days.map(d=>`<option value="${d}" ${d===scheduleDate?'selected':''}>${new Intl.DateTimeFormat('en-US',{timeZone:orderZone(),weekday:'long',month:'short',day:'numeric'}).format(slots.find(t=>slotDay(t)===d))}</option>`).join('')}</select></div><div class="field"><label for="schedule-slot">Time</label><select id="schedule-slot" name="slot">${scheduleOptions(slots,current)}</select></div><p class="small muted">Times use the store’s local timezone. Sample slots follow ${customerStore().opens}–${customerStore().closes} store hours, with preparation time allowed.</p><p class="error" id="schedule-error"></p></div><div class="modal-foot"><button class="btn full" ${slots.length?'':'disabled'}>Confirm order time</button></div></form>`);}
function scheduleOptions(slots=availableSlots(),current=selectedTime()){return slots.filter(t=>slotDay(t)===scheduleDate).map(t=>`<option value="${t}" ${t===current?'selected':''}>${new Intl.DateTimeFormat('en-US',{timeZone:orderZone(),hour:'numeric',minute:'2-digit',timeZoneName:'short'}).format(t)}</option>`).join('');}
function setOrderTime(t){state.fulfillmentAt=t;checkout.scheduledAt=t;checkout.quote=null;const g=state.groupCheckoutId?groupById(state.groupCheckoutId):route().startsWith('group/')?currentGroup():null;if(g&&['Open','Checkout'].includes(g.status))g.scheduledAt=t;save();}
function scheduleField(){const slots=availableSlots(),t=selectedTime();return `<div class="field"><label for="order-time">Order now or schedule for later</label><select id="order-time" name="schedule"><option value="">ASAP · next available</option>${t&&!slots.includes(t)?`<option value="${t}" selected>${scheduleLabel(t)} · Review availability</option>`:''}${slots.map(s=>`<option value="${s}" ${s===t?'selected':''}>${scheduleLabel(s)}</option>`).join('')}</select><button class="text-btn" type="button" data-fast-order="later">Choose day & time →</button></div>`;}
function staffConsole(kind){const store=kind==='store',s=store?managerContext().store:null;return `<header class="staff-console"><div class="row"><button class="icon-btn staff-menu-toggle" data-staff-menu aria-label="Toggle workspace navigation" aria-expanded="false">☰</button><span class="console-avatar">${store?'S':'HQ'}</span><div><strong>${store?esc(s.name):'MOD headquarters'}</strong><small>${store?'Store operations · Today':'Network command center · 6 locations'}</small></div></div><div class="row"><a href="#${store?'store/'+s.id+'/roadmap':'admin/roadmap'}" class="console-roadmap">Features & roadmap</a><button class="btn secondary" data-action="workspace-picker">Switch workspace</button></div></header><nav class="console-shortcuts" aria-label="Workspace shortcuts">${(store?[[`store/${s.id}/today`,'Shift overview'],[`store/${s.id}/kitchen`,'Kitchen'],[`store/${s.id}/orders`,'Orders'],[`store/${s.id}/availability`,'Stock'],[`store/${s.id}/rewards`,'Guest recovery']]:[['admin','Overview'],['admin/compare','Compare stores'],['admin/orders','Orders'],['admin/loyalty','Loyalty'],['admin/campaign-results','Campaign results']]).map(([r,t])=>`<a href="#${r}" class="${route()===r?'active':''}">${t}</a>`).join('')}</nav>`;}
document.addEventListener('click',e=>{if(e.target.closest('[data-staff-menu]')){const open=document.body.classList.toggle('staff-nav-open');e.target.closest('button').setAttribute('aria-expanded',open);return;}const b=e.target.closest('[data-fast-order]');if(!b)return;const a=b.dataset.fastOrder;if(a==='group')return groupCreate();if(a==='later')return schedulePicker();if(a==='now'){setOrderTime(null);render();return toast('ASAP selected.');}if(a==='order')navigate('menu');});
document.addEventListener('change',e=>{if(e.target.id==='schedule-day'){scheduleDate=e.target.value;$('#schedule-slot').innerHTML=scheduleOptions();}if(e.target.id==='order-time'){setOrderTime(Number(e.target.value)||null);checkout.quote=pricingFingerprint();checkout.priceReview=false;}});
document.addEventListener('submit',e=>{if(e.target.dataset.orderingForm!=='schedule')return;e.preventDefault();const t=Number(new FormData(e.target).get('slot'));if(!availableSlots().includes(t))return $('#schedule-error').textContent='That slot is no longer available. Choose another time.';setOrderTime(t);closeModal();render();toast('Order time saved.');});

document.addEventListener('click',e=>{if(e.target.closest('.admin-sidebar a'))document.body.classList.remove('staff-nav-open');});
