'use strict';
const ROADMAP_PHASES=[{id:'1',name:'Current prototype',subtitle:'Explore working flows',outcome:'Demonstrate the complete order, rewards and store-to-HQ journey with sample data.',gate:'Acceptance: customer checkout, group handoff, rewards and refunds reconcile across the three workspaces.'},{id:'2',name:'Phase 2',subtitle:'Guest convenience & service',outcome:'Make more everyday ordering and recovery situations easy to handle.',gate:'Acceptance: edge cases for group changes, pickup, substitutions and item refunds can be demonstrated end to end.'},{id:'3',name:'Phase 3',subtitle:'Loyalty & growth operations',outcome:'Give marketing teams precise control over audiences, incentives and lifecycle campaigns.',gate:'Acceptance: eligibility, budget, consent and holdout rules explain every campaign outcome.'},{id:'4',name:'Phase 4',subtitle:'Network scale & connected operations',outcome:'Extend operational visibility, integrations and commercial reporting across the network.',gate:'Acceptance: store scope, event reconciliation and financial reporting remain consistent at network scale.'}];
const FEATURE_MAP=[
['1','Order','Customer','Menu & customization','46 items, seven categories, pizza builder, meal choices, search, favorites and store availability.','menu'],
['1','Order','Customer','Checkout & wallet','Visible Pickup/Delivery and ASAP/Later controls, seven-day store-timezone scheduling, gift funds, service credit, one reward or deal, simulated card payments.','checkout'],
['1','Order','Customer','Group ordering','Direct Home/Menu group creation, host-paid groups, named contributions, per-person food budgets, readiness, deadlines, shared review and one tracked order. Local participant simulation.','group'],
['1','Order','Customer','Order aftercare','Animated delivery, history, receipts, reorder, support cases, ratings and full-order refund simulation.','orders'],
['1','Order','Customer','Saved preferences','Addresses and named custom pizzas.','account'],
['1','Loyalty','Customer','Rewards & earning','Configurable earning, points rewards, receipt claims, welcome/explorer bonuses and reward activity.','rewards'],
['1','Loyalty','HQ','Program administration','Points per dollar, purchase caps, optional tiers/multipliers and active member controls.','admin/loyalty'],
['1','Loyalty','HQ','Reward qualification','Item/category, minimum spend, tier, date range, store participation and member-use limits.','admin/loyalty'],
['1','Loyalty','HQ','Member audiences & ledger','Search, five dynamic audiences, consent visibility and reasoned points corrections.','admin/loyalty'],
['1','Loyalty','HQ','Coupon lifecycle','Batch/shared/member-issued codes, draft/review/approval, validity, total/member limits, customer wallet and checkout validation.','admin/coupons'],
['1','Loyalty','HQ','Campaign results','Offer orders, attributed customer count, gross/net merchandise, discounts, average order and CSV export.','admin/campaign-results'],
['1','Loyalty','Store','Recovery approvals','Own-store requests, HQ approval, once-only credit/points issuance and observed return tracking.','store/sea/rewards'],
['1','Operations','Store','Shift workspace','Redesigned task workspace: kitchen, orders, availability, ingredients, team/checklist, guest care and order pause/prep settings.','store/sea/today'],
['1','Operations','HQ','Network administration','Redesigned network workspace: six stores, region/store filters, sales comparisons, fulfillment, pricing and order CSV exports.','admin'],
['1','Operations','HQ','Offer configuration','Dollar/percentage campaigns and seeded pizza/cake bundles with participating stores.','admin/campaigns'],
['2','Order','Customer','Expanded group coordination','Guest join screens, invitation/reminder simulations, participant removal after lock, richer group customization and scheduled group deadlines.',''],
['2','Order','Customer','Split contributions','Per-person payment simulation, unpaid/failed contributions, host cover and participant refunds. Current groups have one payer.',''],
['2','Order','Customer','Catering & bulk orders','Headcount bundles, lead times, store capacity review and large-order preparation slots.',''],
['2','Order','Customer','Pickup & curbside','Vehicle details, arrival notification, pickup instructions and collection confirmation.',''],
['2','Order','Customer','Dine-in exploration','Optional store/table QR ordering and pay-at-table demonstrations where appropriate.',''],
['2','Order','Customer','More precise pizza builder','Half/whole placement, premium toppings, sauces, dietary/allergen and nutrition detail.',''],
['2','Order','Customer','Guest account journeys','Guest checkout, enrollment, sample verification, saved payment preferences and account deletion preview.',''],
['2','Order','Customer','Location eligibility','ZIP search, delivery zones, address validation examples, holiday hours and time-specific menus.',''],
['2','Order','Customer','Service edge cases','Payment failure/retry, missing items, substitutions, partial/item refunds and failed delivery.',''],
['2','Operations','Store','Actionable notifications','Sample order/ETA/refund notification inbox and escalation controls.',''],
['3','Loyalty','HQ','Audience builder','AND/OR conditions, exclusions, 30/60/90-day recency, birthday, first-purchase and frozen segments.',''],
['3','Loyalty','HQ','Campaign orchestration','Draft/approval/schedule states for full campaigns, sample Email/SMS/Push reach, consent and frequency caps.',''],
['3','Loyalty','HQ','Promotion engine expansion','BOGO, Buy X Get Y, category exclusions, first-order rules, day/time schedules, priorities and controlled stacking.',''],
['3','Loyalty','HQ','Liability & budgets','Points/reward budgets, incentive-cost assumptions, outstanding liability, expiration and breakage views.',''],
['3','Loyalty','Customer','Lifecycle engagement','Birthday/referral incentives, point expiration warnings, challenges, surveys and gift-card purchase/gifting.',''],
['3','Loyalty','HQ','Automated journeys','Signup, first purchase, inactivity and redemption triggers with queued sample actions.',''],
['3','Loyalty','HQ','Controlled experiments','A/B/holdout assignment, incremental outcomes and contribution assumptions kept separate from attributed sales.',''],
['3','Loyalty','HQ','Fraud & diagnostics','Suspicious redemption queue, barcode/check-in failures, rule evidence and reviewer decisions.',''],
['4','Operations','HQ','Integration event hub','POS, ordering aggregator, delivery partner and payment adapters with simulated inbound/outbound events and retries.',''],
['4','Operations','HQ','Financial reconciliation','Tender settlement, taxes/fees, voids/refunds and franchise fee/debit-memo examples.',''],
['4','Operations','HQ','Delegated administration','Configurable team roles, territories, franchise scope and approval limits.',''],
['4','Operations','HQ','Data center','Field-selected/scheduled exports, backup/restore, warehouse extracts and retention controls.',''],
['4','Operations','HQ','Network capacity','Demand planning, preparation forecasts, stock-aware offers and cross-store exception management.',''],
['4','Loyalty','HQ','Intelligence & assistance','Explainable customer recommendations and campaign planning assistance with human review.',''],
['4','Loyalty','Customer','Optional business models','Paid memberships, merchandise, partner experiences and household benefits after core flows are validated.','']
];
let roadmapPhase='1',roadmapAudience='All',roadmapQuery='';
function stakeholderPage(){const phase=ROADMAP_PHASES.find(p=>p.id===roadmapPhase),rows=FEATURE_MAP.filter(f=>f[0]===roadmapPhase&&(roadmapAudience==='All'||f[2]===roadmapAudience)&&f.slice(1,5).join(' ').toLowerCase().includes(roadmapQuery.toLowerCase()));return `<div class="roadmap-header"><span class="eyebrow red">STAKEHOLDER VIEW</span><h1>What works now.<br>What comes next.</h1><p class="muted">One product view across customer, store and HQ. Current features use sample data; phases 2–4 are proposals, not implemented commitments.</p><div class="row wrap"><a class="btn secondary" href="#group">Try group ordering</a><a class="btn secondary" href="#admin/coupons">Explore coupons</a><button class="text-btn" data-roadmap-print>Print this phase</button></div></div><nav class="phase-nav" aria-label="Product phases">${ROADMAP_PHASES.map(p=>`<button data-phase="${p.id}" class="${p.id===roadmapPhase?'selected':''}" aria-pressed="${p.id===roadmapPhase}"><span>${p.id==='1'?'WORKING NOW':'PROPOSED'}</span><strong>${p.name}</strong><small>${p.subtitle}</small></button>`).join('')}</nav><section class="card phase-outcome"><span class="pill ${roadmapPhase==='1'?'green':''}">${roadmapPhase==='1'?'Implemented prototype':'Proposed scope'}</span><h2>${phase.outcome}</h2><p class="small muted">${phase.gate}</p></section><div class="roadmap-filters"><label class="searchbox">${icon('search')}<input id="roadmap-search" value="${esc(roadmapQuery)}" placeholder="Search this phase" aria-label="Search roadmap"></label><div class="field"><label for="roadmap-audience">View for</label><select id="roadmap-audience">${['All','Customer','Store','HQ'].map(a=>`<option ${a===roadmapAudience?'selected':''}>${a}</option>`).join('')}</select></div></div><div id="roadmap-results" class="roadmap-grid">${roadmapCards(rows)}</div><details class="card discovery-notes"><summary>How Pooja’s discovery shaped this plan</summary><p>The ordering and loyalty scope sheets informed the capability groups. The Chowly group-order reference establishes host-paid ordering. Punch screenshots and the campaign export informed coupon governance, qualification and reporting.</p><p>The sample debit memo is a franchise-fee document, not a coupon-redemption report; financial reconciliation is therefore in phase 4.</p><p>Existing ordering, wallet, loyalty and store workflows are retained. Group orders, coupon lifecycle and campaign results have been added now. Wider automation and integration scenarios remain explicitly proposed.</p><p class="small muted">Source inventory: 161 screenshots, two workbooks and one PDF. Requirements sheets and representative screenshots were reviewed; no source customer data or campaign performance values were imported.</p></details>`;}
function roadmapCards(rows){return rows.map(f=>`<article class="card roadmap-feature"><div class="row between"><span class="pill">${f[1]}</span><span class="small muted">${f[2]}</span></div><h3>${f[3]}</h3><p>${f[4]}</p>${f[5]?`<a class="text-btn" href="#${f[5]}">Explore feature →</a>`:'<span class="small muted">Proposed · not built yet</span>'}</article>`).join('')||'<p class="muted">No features match this filter. Try another audience or search.</p>';}
document.addEventListener('click',e=>{const b=e.target.closest('[data-phase]');if(b){roadmapPhase=b.dataset.phase;roadmapQuery='';render();}if(e.target.closest('[data-roadmap-print]'))window.print();});
document.addEventListener('change',e=>{if(e.target.id==='roadmap-audience'){roadmapAudience=e.target.value;render();}});
document.addEventListener('input',e=>{if(e.target.id==='roadmap-search'){roadmapQuery=e.target.value;$('#roadmap-results').innerHTML=roadmapCards(FEATURE_MAP.filter(f=>f[0]===roadmapPhase&&(roadmapAudience==='All'||f[2]===roadmapAudience)&&f.slice(1,5).join(' ').toLowerCase().includes(roadmapQuery.toLowerCase())));}});
