const {chromium}=require('playwright');const assert=require('node:assert/strict');
(async()=>{const b=await chromium.launch({channel:'chrome',headless:true});try{const p=await b.newPage({viewport:{width:1440,height:1000}}),errors=[];p.on('pageerror',e=>errors.push(e.message));const go=async r=>{await p.goto('http://127.0.0.1:4173/#'+r);await p.waitForTimeout(80)};
 await go('menu');await p.locator('[data-action=customize][data-id=cake]').click();assert.equal(await p.evaluate(()=>state.cart.length),1);
 await go('group');await p.getByRole('button',{name:'Try a sample group'}).click();await p.waitForSelector('.participant-card');const g=await p.evaluate(()=>state.groups[0]);assert.equal(g.people.length,3);assert.equal(await p.locator('.participant-card').count(),3);
 await p.locator('#group-person').selectOption('jamie');assert.equal(await p.locator('[data-group-action=checkout]').count(),0);await p.locator('[data-group-action=ready][data-person=jamie]').click();await p.locator('[data-group-action=add-item][data-person=jamie]').click();await p.locator('#group-product').selectOption('pepperoni');await p.locator('#modal button[type=submit], #modal .modal-foot button').last().click();assert((await p.locator('[data-group-error]').textContent()).includes('over'));await p.locator('#group-product').selectOption('cake');await p.locator('#group-note').fill('Label Jamie');await p.locator('#modal .modal-foot button').click();await p.locator('[data-group-action=ready][data-person=jamie]').click();await p.locator('#group-person').selectOption('host');
 await p.locator('[data-group-action=invite]').click();assert((await p.locator('#group-link').inputValue()).includes(g.id));await p.getByRole('button',{name:'Close dialog'}).click();await p.locator('[data-group-action=checkout]').click();await p.waitForURL(/#checkout$/);await p.waitForSelector('#checkout-form');assert.equal(await p.evaluate(()=>state.cart.length),4);assert.equal(await p.evaluate(()=>state.groupBagBackup.cart[0].id),'cake');assert.equal(await p.locator('.group-label').count(),4);
 await p.locator('#promo-code').fill('TEAM5');await p.locator('[data-action=promo]').click();assert.equal(await p.evaluate(()=>totals().discount),500);await p.locator('#place-order').click();await p.waitForSelector('.map-card');const o=await p.evaluate(()=>state.orders[0]);assert.equal(o.group.people.length,3);assert.equal(o.couponId,'sample-group-coupon');assert.equal(o.items.filter(x=>x.memberName==='Jamie Lee').length,2);assert.equal(await p.evaluate(()=>state.cart[0].id),'cake');assert.equal(await p.evaluate(()=>state.groupCheckoutId),'');assert.equal(await p.evaluate(()=>state.groups[0].status),'Placed');
 await go('admin/orders');await p.locator(`[data-action=ops-order][data-id="${o.id}"]`).click();assert((await p.locator('#modal').textContent()).includes('Jamie Lee'));await p.getByRole('button',{name:'Close dialog'}).click();
 await go('admin/coupons');await p.getByRole('button',{name:'Generate coupons'}).click();await p.locator('#coupon-prefix').fill('POOJADEMO');await p.locator('#coupon-count').fill('2');await p.locator('#coupon-member').selectOption('alex');await p.getByRole('button',{name:'Create draft codes'}).click();const c=await p.evaluate(()=>state.coupons.find(c=>c.code==='POOJADEMO01'));assert.equal(c.status,'Draft');await p.locator(`[data-discovery-action=coupon-submit][data-id="${c.id}"]`).click();await p.locator(`[data-discovery-action=coupon-review][data-id="${c.id}"]`).click();await p.locator('#coupon-note').fill('Approved for the sample walkthrough.');await p.getByRole('button',{name:'Approve coupon'}).click();assert.equal(await p.evaluate(id=>couponState(state.coupons.find(c=>c.id===id)),c.id),'Active');
 await go('deals');assert.equal(await p.locator(`[data-discovery-action=coupon-use][data-id="${c.id}"]`).count(),1);await p.locator(`[data-discovery-action=coupon-use][data-id="${c.id}"]`).click();await go('checkout');await p.locator('#place-order').click();await p.waitForSelector('.map-card');assert.equal(await p.evaluate(()=>state.orders[0].couponId),c.id);const couponOrder=await p.evaluate(()=>state.orders[0].id);assert((await p.evaluate(()=>offerStatus('POOJADEMO01').reason)).includes('allowance'));await p.evaluate(id=>cancelOrder(orderById(id)),couponOrder);assert(!(await p.evaluate(()=>offerStatus('POOJADEMO01').reason||'')).includes('allowance'));
 await go('admin/campaign-results');const download=p.waitForEvent('download');await p.getByRole('button',{name:'Export results CSV'}).click();assert.equal((await download).suggestedFilename(),'mod-campaign-results.csv');
 await go('roadmap');assert.equal(await p.locator('.phase-nav button').count(),4);await p.locator('[data-phase="2"]').click();assert((await p.locator('.phase-outcome').textContent()).includes('Proposed'));assert.equal(await p.locator('.roadmap-feature a').count(),0);await p.locator('#roadmap-audience').selectOption('Customer');await p.locator('#roadmap-search').fill('curbside');assert.equal(await p.locator('.roadmap-feature').count(),1);await p.locator('#roadmap-search').fill('');await p.locator('#roadmap-audience').selectOption('All');
 for(const r of ['roadmap','admin/roadmap','store/sea/roadmap','group','group/'+g.id,'admin/coupons','admin/campaign-results','deals']){await go(r);for(const width of [320,390,768,1440]){await p.setViewportSize({width,height:900});assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),`${r} overflow at ${width}`);}}
 // Open/reopen/cancel/deadline behavior does not lose the ordinary bag.
 await go('group');await p.getByRole('button',{name:'Start a group order',exact:true}).click();await p.locator('#group-name').fill('Friday planning');await p.getByRole('button',{name:'Create group',exact:true}).click();await p.waitForSelector('.participant-card');assert(await p.locator('[data-group-action=checkout]').isDisabled());const fresh=await p.evaluate(()=>state.groups[0]);await p.evaluate(id=>{groupById(id).deadline=Date.now()-1000;render()},fresh.id);assert(await p.locator('[data-group-action=add-item]').isDisabled());await p.locator('[data-group-action=extend]').click();assert(!(await p.locator('[data-group-action=add-item]').isDisabled()));await p.locator('[data-group-action=cancel]').click();assert.equal(await p.evaluate(()=>state.groups[0].status),'Canceled');
 await go('group');await p.getByRole('button',{name:'Try a sample group'}).click();await p.waitForSelector('.participant-card');const reopenId=await p.evaluate(()=>state.groups[0].id);await p.locator('[data-group-action=checkout]').click();await p.waitForURL(/#checkout$/);await p.reload();assert.equal(await p.evaluate(()=>state.groupCheckoutId),reopenId);await p.locator('[data-group-action=reopen]').click();await p.waitForSelector('.participant-card');assert.equal(await p.evaluate(()=>state.groupCheckoutId),'');assert.equal(await p.evaluate(()=>state.groups[0].status),'Open');
 const rejected=await p.evaluate(()=>{const c=state.coupons.find(c=>c.code==='POOJADEMO02');return offerStatus(c.code).reason});assert(rejected.includes('draft'));
 await p.setViewportSize({width:1440,height:1000});await go('admin/roadmap');await p.locator('[data-phase="1"]').click();await p.screenshot({path:'/private/tmp/mod-roadmap.png'});await go('group');await p.getByRole('button',{name:'Try a sample group'}).click();await p.setViewportSize({width:390,height:844});await p.screenshot({path:'/private/tmp/mod-group-mobile.png'});
 assert.deepEqual(errors,[]);console.log('PASS: group participant budgets, ready/host controls, named order lines, coupon checkout, personal bag restoration, store order details, coupon draft/approval/member limits/refund, CSV and stakeholder phases/responsive views.');
 }finally{await b.close()}})().catch(e=>{console.error(e);process.exitCode=1});
