const {chromium}=require('playwright');const assert=require('node:assert/strict');
(async()=>{const b=await chromium.launch({channel:'chrome',headless:true});try{
 const p=await b.newPage({viewport:{width:1440,height:1000}}),errors=[];p.on('pageerror',e=>errors.push(e.message));const go=async r=>{await p.goto('http://127.0.0.1:4173/#'+r);await p.waitForTimeout(70)};const tab=async t=>p.locator(`[data-loyalty-tab=${t}]`).click();
 await go('menu');assert.equal(await p.evaluate(()=>state.menu.length),46);assert.equal(await p.locator('.catalog-section').count(),7);assert(await p.locator('[data-action=customize][data-id=fountain16]').isDisabled());
 await p.waitForFunction(()=>[...document.images].every(i=>i.complete&&i.naturalWidth>0));
 await p.locator('[data-action=customize][data-id=kids-meal]').click();await p.locator('#meal-topping').selectOption('Pepperoni');await p.locator('#meal-drink').selectOption('Milk');await p.getByRole('button',{name:/Add to bag/}).click();assert.equal(await p.evaluate(()=>state.cart[0].options.drink),'Milk');
 await p.locator('[data-action=customize][data-id=custom-salad]').click();await p.locator('#meal-greens').selectOption('Arugula');await p.getByLabel('Feta',{exact:true}).check();await p.getByRole('button',{name:/Add to bag/}).click();assert.equal(await p.evaluate(()=>state.cart[1].options.greens),'Arugula');
 await p.locator('[data-action=customize][data-id=cake-pop-duo]').click();await p.locator('#meal-second').selectOption('Pumpkin spice');await p.getByRole('button',{name:/Add to bag/}).click();assert.equal(await p.evaluate(()=>state.cart[2].options.second),'Pumpkin spice');
 await p.locator('#menu-search').fill('water');assert.equal(await p.locator('.product').count(),1);await p.locator('#menu-search').fill('');
 await go('admin/loyalty');await p.locator('#loyalty-rate').fill('2');await p.locator('#loyalty-dailyCap').fill('50');await p.getByRole('button',{name:'Save program rules'}).click();assert.equal(await p.evaluate(()=>state.loyalty.rate),2);
 await tab('catalog');await p.getByRole('button',{name:'Create reward',exact:true}).click();await p.locator('#reward-name').fill('A fresh salad reward');await p.locator('#reward-desc').fill('Up to $10 off one salad at Seattle.');await p.locator('#loyalty-points').fill('50');await p.locator('#reward-kind').selectOption('item');await p.locator('#loyalty-value').fill('10');await p.locator('#reward-category').selectOption('Salads');await p.locator('#loyalty-limit').fill('1');for(const id of ['bel','por','aus','den','phx'])await p.locator(`input[name=stores][value=${id}]`).uncheck();await p.getByRole('button',{name:'Save reward',exact:true}).click();const reward=await p.evaluate(()=>state.rewardCatalog.find(r=>r.name==='A fresh salad reward'));assert.deepEqual(reward.stores,['sea']);
 await go('rewards');await p.locator(`[data-action=reward][data-id="${reward.id}"]`).click();await go('checkout');assert.equal(await p.evaluate(()=>totals().discount),1000);await p.locator('#place-order').click();await p.waitForSelector('.map-card');const placed=await p.evaluate(()=>state.orders[0]);assert.equal(placed.rewardId,reward.id);assert.equal(placed.earnRate,2);assert.equal(await p.evaluate(()=>state.points),75);
 // A placed order keeps its earning rate even after HQ edits the program.
 await go('admin/loyalty');await tab('program');await p.locator('#loyalty-rate').fill('3');await p.getByRole('button',{name:'Save program rules'}).click();await go('track/'+placed.id);for(let n=0;n<4;n++)await p.locator('[data-action=advance]').click();const completed=await p.evaluate(()=>state.orders[0]);assert.equal(completed.pointsEarned,32);assert.equal(await p.evaluate(()=>state.points),107);assert.equal(await p.evaluate(id=>rewardAvailable(state.rewardCatalog.find(r=>r.id===id)),reward.id),'Member limit reached');
 // Refund is the inverse of earning and redemption and reopens the usage allowance.
 await p.evaluate(id=>cancelOrder(orderById(id)),placed.id);assert.equal(await p.evaluate(()=>state.points),125);assert.equal(await p.evaluate(id=>rewardAvailable(state.rewardCatalog.find(r=>r.id===id)),reward.id),'');
 await go('store/sea/rewards');assert.equal(await p.locator('[data-loyalty-action=edit-reward]').count(),0);await p.getByRole('button',{name:'Request recovery'}).click();await p.locator('#recovery-member').selectOption('alex');await p.locator('#loyalty-amount').fill('30');await p.locator('#recovery-reason').fill('Late handoff, please make this right.');await p.getByRole('button',{name:'Send to HQ for review'}).click();assert.equal(await p.evaluate(()=>state.points),125);const request=await p.evaluate(()=>state.recovery[0]);assert.equal(request.status,'Pending');
 await go('store/bel/rewards');assert.equal(await p.getByText('Late handoff, please make this right.',{exact:true}).count(),0);
 await go('admin/loyalty');await tab('recovery');await p.locator(`[data-loyalty-action=recovery-review][data-id="${request.id}"]`).click();await p.locator('#decision-note').fill('Approved after reviewing the handoff.');await p.getByRole('button',{name:'Confirm decision'}).click();assert.equal(await p.evaluate(()=>state.points),155);assert.equal(await p.evaluate(id=>state.loyaltyLedger.filter(l=>l.type==='recovery'&&l.customer==='alex').length,request.id),1);
 await tab('members');await p.locator('[data-loyalty-action=member][data-id=alex]').click();await p.locator('#loyalty-delta').fill('-999');await p.locator('#adjust-reason').fill('Test correction');await p.getByRole('button',{name:'Record adjustment'}).click();assert((await p.locator('[data-loyalty-error]').textContent()).includes('Not enough'));assert.equal(await p.evaluate(()=>state.points),155);await p.locator('#loyalty-delta').fill('10');await p.getByRole('button',{name:'Record adjustment'}).click();assert.equal(await p.evaluate(()=>state.points),165);
 // Purchase cap and store eligibility apply in the shared checkout engine.
 assert.equal(await p.evaluate(id=>rewardAvailable(state.rewardCatalog.find(r=>r.id===id),'alex','bel'),reward.id),'Not at this store');
 const cap=await p.evaluate(()=>{const snapshot=structuredClone(state);const o={id:'CAP-CHECK',customerId:'alex',storeId:'sea',earnRate:3,earnCap:50,totals:{subtotal:10000,discount:0,merchandiseDiscount:0}};awardOrderPoints(o);const result=o.pointsEarned;state=snapshot;return result;});assert.equal(cap,18);
 const paused=await p.evaluate(id=>{state.memberMeta.alex.active=false;const reason=rewardAvailable(state.rewardCatalog.find(r=>r.id===id));state.memberMeta.alex.active=true;return reason;},reward.id);assert.equal(paused,'Membership paused');
 // Rule-level edge cases, using the same engine the UI calls.
 await p.evaluate(id=>{const r=state.rewardCatalog.find(r=>r.id===id);r.end='2000-01-01';},reward.id);assert.equal(await p.evaluate(id=>rewardAvailable(state.rewardCatalog.find(r=>r.id===id)),reward.id),'Reward expired');await p.evaluate(id=>{const r=state.rewardCatalog.find(r=>r.id===id);r.end='';r.tier='Gold';},reward.id);assert.equal(await p.evaluate(id=>rewardAvailable(state.rewardCatalog.find(r=>r.id===id)),reward.id),'Gold members only');await p.evaluate(id=>{state.rewardCatalog.find(r=>r.id===id).tier='Member';},reward.id);
 await p.reload();assert.equal(await p.evaluate(()=>state.points),165);assert.equal(await p.evaluate(()=>state.menu.length),46);
 for(const r of ['menu','cart','rewards','admin/loyalty','store/sea/rewards']){await go(r);for(const width of [320,390,768,1440]){await p.setViewportSize({width,height:900});assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),`${r} overflow ${width}`);}}
 await p.setViewportSize({width:1440,height:1000});await go('admin/loyalty');for(const t of ['program','catalog','members','recovery','report']){await tab(t);await p.setViewportSize({width:390,height:844});assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),`${t} overflow`);await p.setViewportSize({width:1440,height:1000});}await tab('catalog');await p.screenshot({path:'/private/tmp/mod-loyalty-admin.png'});await go('menu');await p.setViewportSize({width:390,height:844});await p.screenshot({path:'/private/tmp/mod-expanded-menu.png'});assert.deepEqual(errors,[]);console.log('PASS: 46-item menu, seven categories, meal choices, pickup rules, reward editor and checkout, earning snapshot, refund inverse, usage limits, dates, tiers, adjustment validation, store recovery/HQ approval, persistence and responsive screens.');
 }finally{await b.close()}})().catch(e=>{console.error(e);process.exitCode=1});
